### ISSUE TITLE
运行DemoWithStaticLib报错

### ISSUE THREAD

**Issue by CoderMaurice** [fengjian0106/hed-tutorial-for-document-scanning#1]
<img width="823" alt="wx20180605-092813 2x" src="https://user-images.githubusercontent.com/22311615/40949890-d3709676-68a2-11e8-8e48-053ec94c51de.png">

运行demo之后报这个错
里面的库都没有动过

**Comment by CoderMaurice** [comment]
找到原因了
DemoWithStaticLib里编译好的lib因为体积太大已经下载不下来了
所以无法运行
lib需要自己去编译

**Comment by fengjian0106** [comment]
@CoderMaurice 和 [https://github.com/fengjian0106/hed-tutorial-for-document-scanning/issues/2](https://github.com/fengjian0106/hed-tutorial-for-document-scanning/issues/2) 这个是同样的问题，都是 git lfs 引起的，我已经移除 lfs 了，重新 clone 一遍代码试试。
