### ISSUE TITLE
FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)

### ISSUE THREAD

**Issue by endy-see** [fengjian0106/hed-tutorial-for-document-scanning#10]
hi, when i run your code with my own dataset, it's crashed with below error:

OutOfRangeError (see above for traceback): FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/fifo_queue, batch/n)]]

my dataset total 1996 color img and 1996 gray_thresh img, and i set batch=1, it's always crash at same point--at the 1994th img. I accept it's certainly almost run out the hole dataset,but why can't it reture from the 1th data to retrain again? Besize, i set my iterations=2000, but it's always crash at the 620th iterations and notice me no data. I want to know can it reuse my dataset when there is no sufficient data? Please help , Thanks!

**Comment by fengjian0106** [comment]
看上去是某一行数据中的元素个数不符合预期，你可以再检查一下你的数据。
"why can't it reture from the 1th data to retrain again" 这是 TensorFlow 框架层面的原因，你可以绕开他，把 csv 文件里的内容，重复复制粘贴很多次，这样就相当于一个比较大的 dataset 了。而且还可以利用 shuf / gshuf 命令行工具提前对 csv 文件的内容做一个随机乱序的预处理

**Comment by chaoyueziji** [comment]
请问解决了嘛？

**Comment by chaoyueziji** [comment]
好像是数据量过少的原因，建议增加数据量

**Comment by chaoyueziji** [comment]
1,可能是数据过少原因
2,其次可以打印一下读取图片的路径，看下是否读取对。sess = tf.Session() print(sess.run(image_path))
