### ISSUE TITLE
轮廓线条太粗

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#13]
![debug1](https://user-images.githubusercontent.com/17869361/43709812-67fc757a-99a0-11e8-9d0c-0d7857cd29b7.jpg)
![simulator screen shot - iphone 6s - 2018-08-01 at 19 50 45](https://user-images.githubusercontent.com/17869361/43709897-ae43b552-99a0-11e8-983a-d2ed8769c4db.png)
![simulator screen shot - iphone 6s - 2018-08-01 at 19 51 05](https://user-images.githubusercontent.com/17869361/43710150-695a9068-99a1-11e8-8542-3c2088077810.png)
![debug4](https://user-images.githubusercontent.com/17869361/43710165-70da506c-99a1-11e8-8b11-b0bb342e9936.jpg)
android 和 ios 都测过很多图片都是左边和顶部都会有一些间隙，但右边和底部匹配的很好。也看过你的算法也没有太大的问题。
我的猜测还是觉得识别出来的线条太粗了造成的。虽然在debug_img没有间隙，绘制的线条本身也很粗。
但在裁剪的时候是以像素为单位的。
轮廓识别还能有优化的空间，变得更细？

**Comment by fengjian0106** [comment]
目前没有好的办法进一步优化了，边缘检测线比较粗，主要是两个原因：
1、我的训练样本是合成的，有一定的失真度。理论上来说，HED网络检测边缘线，其实就是对边缘位置处的像素做像素级的分类，然而我合成的样本，并不是完美匹配到边缘线上的，只是把近似的4个顶点直接用线段连接了起来。如果能够改善训练样本的质量，比如人工手动标注一批训练样本，把文档的边缘线画出来，这样的效果可能会好一些。
2、HED 使用了多融合的网络结构，也就是意味着在越靠后的 layer 里，检测出来的 feature map 的 size 是越小的，经过 deconv 或 upsample 后才能达到 input image 的尺寸，在这个运算过程中，边缘线的宽度也会变的更大一些，所以最终经过融合得到的边缘线比较粗。

如果能够有更高质量的标注样本，其实也可以使用其他的网络结构来实现这个边缘检测任务，我用 UNet 尝试过直接做像素级的分类，用我合成的样本训练后，也能检测到更细的边缘线，但是边缘线中缺失的部分就比较多，后续流程中的OpenCV算法就不太容易补全这种缺失的部分。但是我觉得，只要能够有更真实的样本数据，直接做像素级的分类，是可以得到比较完整并且更细的边缘线的。

**Comment by weinixuehao** [comment]
我反编译过全能只能扫描王，它的so size怎么那么小。不知道它是用的什么算法？

**Comment by fengjian0106** [comment]
可能只是基于 OpenCV 实现的算法，我这边QQMail里面，第一版算法也是只用到了 OpenCV，因为效果不够好，才尝试了神经网络算法。现在在 QQMail 里面，是两套引擎一起使用的。

**Comment by renmoqiqi** [comment]
咨询个问题，大佬你这个裁剪是作者demo改的么，我输入静态图片，很糊
