### ISSUE TITLE
重新训练模型大概需要多久时间？

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#14]
因为线段比较粗的问题，所以想打算重新训练模型。借此也了解一下人工智能相关开发。
但是因为我之前从未在人工智能这块有涉猎，所以一开始只是基于现有的模型，做开发。然后部署了android版的。
所以我需要做个时间评估，从0开始搞这块需要多久时间？或者你从一开始搞这块花了多久时间。

**Comment by fengjian0106** [comment]
用我这份代码直接训练的话，在 iMac 上直接用 CPU 训练，2天左右就够了。
如果是从0开始，想学习原理，看懂代码或者自己编写代码的话，周期就比较长了。

**Comment by weinixuehao** [comment]
你用了多久时间？在搞这块前，之前过这块相关基础？可以给个学习路线？

**Comment by fengjian0106** [comment]
没有这方面的基础，我是断断续续的学的，以年为单位吧。如果你集中一段时间学习的话，3~6个月应该可以初步上手。
先学习最基本的分类模型，然后再学习不同task的网络结构，学习的过程中不断的查漏补缺，学习各种基础知识和概念。

**Comment by weinixuehao** [comment]
明白了，感谢。多问一句你是做qq email的？

**Comment by weinixuehao** [comment]
@fengjian0106 有个最少学习线路么？
我的数学很菜，我在想应该不需要把数学重新搞一把吧，只是处理具体的任务的时候，了解与该任务有关的数学知识点就好，关键需要把整体的开发流程和专业术语搞清楚？
平时开发任务，都是喜欢直接上，遇到问题解决问题方式去学习，去专门系统去学习一门技术，挺乏味。可能真的就是从入门到放弃了。

**Comment by fengjian0106** [comment]
不需要完整的重新搞一遍数学，先学会使用框架，然后尽量理解不同的函数代表的含义，先从工程的角度把整套东西使用起来。遇到有些公式的时候，尽量尝试去理解，但是不一定要自己推导。恩，我在qqmail团队。
