### ISSUE TITLE
关于训练图片

### ISSUE THREAD

**Issue by moondaiy** [fengjian0106/hed-tutorial-for-document-scanning#15]
作者你好, 我对这个工作很敢兴趣, 想自己训练一个网络, 请问下, 你贡献的那个模型, 在训练的时候 我看文章报道是合成了大概8万张 人为图片, 那请问下 实际在训练的时候, 就只用到这8万张合成图片?还是包含比如其他通用边缘检测例如BSDS500 这样的数据集

**Comment by fengjian0106** [comment]
只使用了这8万张合成的图片。通用数据集虽然也是检测边缘，但是边缘的形状和我的需求中期望的形状是不一样的，所以不需要使用通用数据集。
