### ISSUE TITLE
关于输出

### ISSUE THREAD

**Issue by moondaiy** [fengjian0106/hed-tutorial-for-document-scanning#16]
作者你好:请问下,在hed中 最终的 fused 输出不需要进行sigmod 压缩像素点到0-1之间么? 你的loss来看 是使用了 tf.nn.weighted_cross_entropy_with_logits 里面是对 logis 进行sigmod 压缩的 这点不是太理解..

**Comment by fengjian0106** [comment]
训练过程中，就是像你说的这样，在 tf.nn.weighted_cross_entropy_with_logits 里面是有 sigmod 的过程的。
在前向推导的过程中，理论上来说，也应该使用 sigmod 让输出值在 0~1.0 之间，但是对于我的实际需求，其实就是对每一个像素做一个二分类，要么就是背景像素，要么就是边缘像素，所以对于 0~1.0 之间的值，还需要做一个 threshold 分割。在 sigmod 之后或之前做 threshold 分割，没有太大的区别，所以就把 signod 省掉了。

**Comment by moondaiy** [comment]
嗯, 是这个意思,明白了 3ks哈~~
