### ISSUE TITLE
图片尺寸问题

### ISSUE THREAD

**Issue by fangxu622** [fengjian0106/hed-tutorial-for-document-scanning#17]
@fengjian0106  您好，我制作了你的那个数据集 3个多G，只不过中途运行退出了。不知道是不是这个大小。也成功运行了网络。但现在有一个小疑问，原始HED caffe代码，训练数据好像可以是任意尺寸，我想拿BSDS 数据来训练，就运行出错了。所以我想请教一下，如果要改进代码使得适应任意尺寸的数据？我想到最简单的方法就是吧数据全部缩放256 256 ，或者是我在tf中的指定一个尺寸 ，然后将输出结果缩放到原始尺寸，但应该不是这样做的吧？因为无论我怎么该const.height 与 width ,只能适应一个尺寸。

**Comment by fangxu622** [comment]
应该就是在这个地方，如何恢复到原始尺寸的大小 ，而不是制定一个大小
```
image_tensor = tf.reshape(image_tensor, [const.image_height, const.image_width, 3])
annotation_tensor = tf.reshape(annotation_tensor, [const.image_height, const.image_width, 1])
```

**Comment by fengjian0106** [comment]
你可以把你的数据先做一边预处理，统一缩放成一个固定的尺寸上，顺便可以做一些数据增强的动作，比如旋转一下图片、随机裁剪一下等等。
因为网络中不止一个地方用到了 const.height 和 const.width，所以把这两个值设计成了常量，在有些网络结构中，也可以不限定在特定的一个尺寸上，而是可以让网络适应不同的 input image size，这个和网络结构有关系了。

**Comment by fengjian0106** [comment]
``` 这里调用 resize，是因为 tensorflow 不知道 image 的大小，一定要手动设置一下才行
# decode之后，一定要设置 image 的大小，或者 resize 到一个size，否则会 crash
image_tensor = tf.reshape(image_tensor, [const.image_height, const.image_width, 3])
annotation_tensor = tf.reshape(annotation_tensor, [const.image_height, const.image_width, 1])
```

理论上来说，在这个位置可以使用 resize 操作调整image的大小，但是 resize 的时候，annotation_tensor 里面的边缘线会被进行插值运算，有可能会影响边缘线的粗细或平滑程度，把这个 resize 动作放到一个单独的预处理程序中更方便调试，而且预处理程序不一定要局限在python code中，可以使用任何手段来做这个预处理，一切都是以实现需求为目的。

**Comment by fangxu622** [comment]
```
    # http://stackoverflow.com/questions/34746777/why-do-i-get-valueerror-image-must-be-fully-defined-when-transforming-im
    # http://stackoverflow.com/questions/37772329/tensorflow-tensor-set-shape-valueerror-image-must-be-fully-defined
    # image is jpg, annotation is png
    image_tensor = tf.image.decode_jpeg(image_content, channels=3)
    annotation_tensor = tf.image.decode_png(annotation_content, channels=1)
    # decode之后，一定要设置 image 的大小，或者 resize 到一个size，否则会 crash

    #with tf.Session() as sess:
    #    const.image_height = image_tensor.eval().shape[0]
    #    const.image_width = image_tensor.eval().shape[1]

    image_tensor = tf.reshape(image_tensor, [const.image_height, const.image_width, 3])
    annotation_tensor = tf.reshape(annotation_tensor, [const.image_height, const.image_width, 1])

```

这个地方就是我 不解得地方，由于希望能训练任意尺寸图像，所以batch _size 必须为1，这个时候decode_jpeg之后需要指定图像尺寸，否则提示 All shapes must be fully defined，在这个地方想如何指定为原始尺寸大小。

**Comment by fangxu622** [comment]
所以 您在实际应用中是如何解决固定尺寸问题？手机拍出来的图像不是固定的尺寸的呀 ，使用该模型的时候把所有图像都是先缩放至256 或固定尺寸进行预测吗？

···
image_tensor = tf.image.resize_images(image_tensor, [const.image_height, const.image_width])
···
往往需要在这个地方预先知道图像的原始尺寸吧

**Comment by fengjian0106** [comment]
> ```
>     # http://stackoverflow.com/questions/34746777/why-do-i-get-valueerror-image-must-be-fully-defined-when-transforming-im
>     # http://stackoverflow.com/questions/37772329/tensorflow-tensor-set-shape-valueerror-image-must-be-fully-defined
>     # image is jpg, annotation is png
>     image_tensor = tf.image.decode_jpeg(image_content, channels=3)
>     annotation_tensor = tf.image.decode_png(annotation_content, channels=1)
>     # decode之后，一定要设置 image 的大小，或者 resize 到一个size，否则会 crash
> 
>     #with tf.Session() as sess:
>     #    const.image_height = image_tensor.eval().shape[0]
>     #    const.image_width = image_tensor.eval().shape[1]
> 
>     image_tensor = tf.reshape(image_tensor, [const.image_height, const.image_width, 3])
>     annotation_tensor = tf.reshape(annotation_tensor, [const.image_height, const.image_width, 1])
> ```
> 这个地方就是我 不解得地方，由于希望能训练任意尺寸图像，所以batch _size 必须为1，这个时候decode_jpeg之后需要指定图像尺寸，否则提示 All shapes must be fully defined，在这个地方想如何指定为原始尺寸大小。

不要指定为原始尺寸大小，而是先用另外一个程序，对所有的图片都做一边处理，缩放成同样的大小，如果长宽比例不一样，还可以考虑在缩放的同时，padding成相同大小的图片
