### ISSUE TITLE
android 端实时监测效果不佳

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#18]
单张识别还可以，做成拍照实时预览识别，卡顿明显，尤其在比较差的机子上。
请问你在android是怎么处理的？

**Comment by fengjian0106** [comment]
Android端的情况比较复杂，机型差异比较明显，可以尝试减小 image 的 size，比如从 256 * 256 缩小为 224 * 224，也可以尝试把 mobilenet_v2_style_hed 里面的卷积核的数量再减少一些，适当的降低准确性来换取执行速度。特别差的机型上，我这边其实也并没有跑这个神经网络算法的，会回退到使用以前的完全基于OpenCV的旧版算法

**Comment by dustturtle** [comment]
基于openCV的完整算法有代码吗？请教一下@fengjian0106
