### ISSUE TITLE
模型转换的问题

### ISSUE THREAD

**Issue by ljdang** [fengjian0106/hed-tutorial-for-document-scanning#19]
利用tf.contrib.lite.TocoConverter.from_frozen_graph将提供的hed_graph.pb模型转换成.tflite，一直不成功，看提示应该是与Batch normalization相关。
另外，在freeze_model.py文件中is_training_placeholder是不是可以省略，dsn_fuse, dsn1, dsn2, dsn3, dsn4, dsn5 = mobilenet_v2_style_hed(image_float, batch_size, False)，这里直接给False就行？

**Comment by fengjian0106** [comment]
之前我尝试过tflite，也是不成功，这个跟 tflite 支持的 operation 有关，tflite 支持的始终只是 完整op 的一个子集，遇到转换失败是很正常的。目前最新版本的 tflite 我还没有尝试过。
is_training_placeholder 不能省略，因为它是 graph 的一部分。

**Comment by ljdang** [comment]
@fengjian0106 我直接设置为False是可以转换成功的，难道不是给定固定值，不设置placeholder了，那就不是graph的一部分吗？我先试试看部署有没有问题。

**Comment by fengjian0106** [comment]
恩，就是在部署的时候，还需要这个 placeholder，至少用 C++ 部署的时候是需要的，python的我不确定了，你可以试试看
