### ISSUE TITLE
git lfs clone error

### ISSUE THREAD

**Issue by amit2319** [fengjian0106/hed-tutorial-for-document-scanning#2]
**batch response**: This repository is over its data quota. Purchase more data packs to restore access.
**error**: failed to fetch some objects from 'https://github.com/fengjian0106/hed-tutorial-for-document-scanning.git/info/lfs'

**Comment by fengjian0106** [comment]
@amit2319 hi, I'm not using git lfs now, and I add some shell script to merge large size file. So try again, just `git clone https://github.com/fengjian0106/hed-tutorial-for-document-scanning`
