### ISSUE TITLE
合并临近直线问题

### ISSUE THREAD

**Issue by ljdang** [fengjian0106/hed-tutorial-for-document-scanning#20]
在文件fm_ocr_scanner.cpp中合并临近直线部分，没有使用合并后的结果。
https://github.com/fengjian0106/hed-tutorial-for-document-scanning/blob/ddd65cb3f6c9fcb5703bca2442ed39948468ad4e/ios_demo/FMHEDNet/FMHEDNet/fm_ocr_scanner.cpp#L554
这代码块是不是应该使用merged_ref_line_and_segment_pairs？

**Comment by fengjian0106** [comment]
我找不到当时调试时候的debug信息了，有可能是我反复调试后，发现不合并临近直线也能做到比较好的效果，就忽略了这个合并的动作了，这样可以加快运算的速度。不过这个没有太大的关系，你可以切换成使用 merged_ref_line_and_segment_pairs，然后对比看看实际的运行效果有没有明显的差异。
再次感谢你提出这个问题，当时review代码的时候疏忽了这个细节。
