### ISSUE TITLE
关于图片合成

### ISSUE THREAD

**Issue by andk11** [fengjian0106/hed-tutorial-for-document-scanning#22]
你好，打扰致歉。
在学习过程中遇到一些问题，希望能指点一二。
1.为什么要在iPhone模拟器上进行图片合成？
2.如果是安卓真机要怎么合成图片，依然可以在iPhone模拟器上进行合成吗？
不胜感激。
@fengjian0106

**Comment by fengjian0106** [comment]
1. OpenCV 不能处理透明图层，合成的效果不够好，所以想使用 OpenGL 来合成
2. 使用原始的 OpenGL 来编写代码，开发难度比较大
3. 我比较熟悉 iOS 开发，所以用 iOS 环境来合成图片，iOS 的 UIView 和 CALayer，本质上就是基于 OpenGL 或类似技术的
4. 如果是安卓，理论上也是可以合成的，用 Android 的 View 应该就可以了

**Comment by andk11** [comment]
深夜打扰致歉（对又是我
还是样本合成的问题 
想知道在2.2步结束后我们会有哪些类型的图片生成
![image](https://user-images.githubusercontent.com/44542923/49389605-b5df5180-f761-11e8-826d-d76eeaeef734.png)

因为在训练的过程中报OutOfRangeError错误
排查之后发现是数据没有读进来
所以想应该还是数据集的问题

**Comment by fengjian0106** [comment]
最终生成的图有png格式的边缘图，也有jpg格式的彩色原图。
你可以在 sample_images/rect_images 和 sample_images/background_images 目录里各自只存放两三张图片，然后运行代码看看生成的图片有什么内容，如果有 error，可以把 log 贴上来看看

**Comment by andk11** [comment]
训练的时候报的是这个错
![image](https://user-images.githubusercontent.com/44542923/49418260-33d04680-f7bc-11e8-8338-a7eb9a8c2f4a.png)
我查了说是参数错误
但我对tensorflow还不是很熟悉
所以找不到是哪里出了问题T T

**Comment by fengjian0106** [comment]
看日志的话，是csv文件里面没有内容导致的，你生成完样本图片，先确认一下csv文件里是否有内容，然后调用train_hed.py的时候，也要确认一下是否指定了正确的csv文件的路径

**Comment by andk11** [comment]
csv文件和路径都检查了的
有一个输出感觉有点奇怪
这个cost是空的
![image](https://user-images.githubusercontent.com/44542923/49451510-49745900-f81a-11e8-8002-72d86eefb12f.png)
还有一个报错信息 不是很明白
![tim 20181204230817](https://user-images.githubusercontent.com/44542923/49451410-1cc04180-f81a-11e8-9eb3-202c183e1251.png)

**Comment by andk11** [comment]
啊是这样的 现在已经确定了是没有从csv中读入任何数据
但是路径和文件都检查过了
找不到问题出在哪里

**Comment by andk11** [comment]
我重新生成了一下csv文件
在最后写入的时候
报了下面这个错
![image](https://user-images.githubusercontent.com/44542923/49454030-462f9c00-f81f-11e8-8cfa-5476f18dbf39.png)
原因是python3中要用w打开而不是wb 
改成w打开之后写进去的数据类型就是str而不是bytes类型了
想问下这样会有影响吗

**Comment by fengjian0106** [comment]
呃。。。这份代码是基于Python2开发和调试的，没有在Python3下严格的测试过，可能会出现一些兼容性的问题，你如果只是想快速的运行起来的话，建议换成Python2。

**Comment by lionandbull** [comment]
> csv文件和路径都检查了的
> 有一个输出感觉有点奇怪
> 这个cost是空的
> ![image](https://user-images.githubusercontent.com/44542923/49451510-49745900-f81a-11e8-8002-72d86eefb12f.png)
> 还有一个报错信息 不是很明白
> ![tim 20181204230817](https://user-images.githubusercontent.com/44542923/49451410-1cc04180-f81a-11e8-9eb3-202c183e1251.png)

你好，请问这个cost（）本应该是空的还是应该有shape的？
