### ISSUE TITLE
IsSegmentsHasSameSegment过滤条件

### ISSUE THREAD

**Issue by wbzlop** [fengjian0106/hed-tutorial-for-document-scanning#23]
原代码是：
`if (diff < kSameSegmentsMaxAngle) {
            return true;
        }`
这样角度0和178这样相似的线会被过滤掉，所以不应该是下面的过滤条件吗？
`if (diff < kSameSegmentsMaxAngle || diff > 85) {
            return true;
}`

**Comment by fengjian0106** [comment]
这个 if 语句前面有
diff = diff % 90;//修正到0~90度
这样的一行代码，diff的取值已经被限制在 0 ~ 90 度之间了，所以 diff > 85 的时候，这两根直线是接近于互相垂直的状态的

**Comment by wbzlop** [comment]
int angle_a = GetAngleOfLine(seg);// angle_a = 0
int angle_b = GetAngleOfLine(segment);// angle_b = 178

int diff = std::abs(angle_a - angle_b);//diff = 178
diff = diff % 90;//diff = 88

所以 0° 与 178°接近互相垂直？我现在是进入了某些思维误区了吗？？？

**Comment by fengjian0106** [comment]
已经 fix 了，十分感谢！

**Comment by xiexyao** [comment]
您好，在IsSegmentsHasSameSegment代码中现在是：
![image](https://user-images.githubusercontent.com/24327607/59994414-5ce7f400-9686-11e9-97f7-d516e1c07562.png)，如果两个角度分别是0和89度，按照这个代码是会判断为True的吧，是我哪里弄错了吗？

**Comment by fengjian0106** [comment]
@xiexyao 
std::tuple<bool, std::vector<cv::Point>, std::vector<cv::Mat> > ProcessEdgeImage(cv::Mat edge_image, cv::Mat color_image, bool draw_debug_image)
这个函数返回的tuple里的 std::vector<cv::Mat>，里面绘制了中间过程中检测到的线段和交叉点，你可以在这些Mat上看一下效果。
另外，IsRectCornersReasonable 在做过滤的时候，那些过滤条件也是互补的，有一定的容错性。
