### ISSUE TITLE
线段延展成参考线

### ISSUE THREAD

**Issue by ljdang** [fengjian0106/hed-tutorial-for-document-scanning#24]
线段延展成参考线函数GetRefLine好像有点问题，在OpenCV坐标系中y轴方向是向下的，最后一个else分支这逻辑会导致一些参考线段在图像外部？
另外，判断参考线是否相近的函数IsTwoRefLineCloseToEachOther好像也有问题，例如下图所示，这情况函数的返回应该是true，但实际却不相近，不知道是不是哪里理解错了？
![p81114-174123](https://user-images.githubusercontent.com/21071150/48474822-5c58c680-e836-11e8-973d-c4eee471a816.jpg)

**Comment by fengjian0106** [comment]
十分感谢提出这些问题，你遇到的这些问题，我之前也是没有注意到过的，基于OpenCV编写的这部分代码，业务逻辑上的确是比较繁琐，很容易遗漏掉一些案例场景。如果你有兴趣的话，也可以尝试修改遇到的这些bug，或者是尝试按照自己的思路来编写这部分的代码。

不过当时在设计这部分代码的时候，也是考虑了一定的容错性的。这里做的事情，相当于是在层层过滤，把最有可能组成四边形的线段逐层过滤出来，即便某一层遇到了一些预料之外的状况而未能正确处理，在后续的流程中也是有可能被再次过滤掉的，编写代码和调试代码的过程，也是在不断的debug过程中，凭经验和感觉对代码进行调整，最终达到一个可以接受的效果。

其实也很明显的对比了两种开发手段的差异，一种是机器学习手段，不需要对系统建立精确的数学或物理模型，而是用线性的矩阵变换和非线性的激活函数来近似模拟业务模型，另一种就是这部分OpenCV算法使用的精确建模的手段。

我个人也一直在学习神经网络的各种模型，其实最近还发现了一些新的线索--heatmaps，也许是可以做到用神经网络一步到位直接预测矩形的四个点的(有点打脸我之前博客里写的一个结论，无法直接用神经网络端到端的预测四边形顶点坐标)，只不过最近一直在忙于做其他的事情，还没有时间去验证这个新的想法。

**Comment by ljdang** [comment]
@fengjian0106 是的，OpenCV算法设计这部分要考虑的情况确实比较多，也是在调试过程中发现的这些问题。关于heatmaps方法，之前有看到用于做人体/人脸关键点的检测，效果比较不错，之后可以尝试，看看适不适合这种场景。
另外，想请教一下，QQ邮箱的so文件好小，是怎么裁剪OpenCV库的呢，我这边只编译了core和imgproc模块，就有2M多的体积？

**Comment by fengjian0106** [comment]
你是说Android版的OpenCV的动态库吗？

**Comment by ljdang** [comment]
@fengjian0106 恩恩，Android版的动态库。

**Comment by fengjian0106** [comment]
问了一下同事，我们的 Android 版 OpenCV，没有人工裁剪过的，也就是在 gradle 编译的最后一步用 strip 处理了一下。另外，我不知道你看到的是哪一个 so 动态库的 size，我们的 apk 包里的 so 是很小，因为 OpenCV 的 so 是动态下发的。

**Comment by ljdang** [comment]
@fengjian0106 明白了，还以为所有的so库都放在apk包中，非常感谢！

**Comment by fengjian0106** [comment]
> @fengjian0106 明白了，还以为所有的so库都放在apk包中，非常感谢！

不用客气
