### ISSUE TITLE
关于样本合成

### ISSUE THREAD

**Issue by Timthony** [fengjian0106/hed-tutorial-for-document-scanning#25]
请问样本合成的时候，样本有了，但是样本对应的标签，也就是边缘是怎么得到的呢？

**Comment by fengjian0106** [comment]
合成样本的时候，是可以计算出四边形顶点的坐标的，有了坐标，就可以在标签图上绘制边缘线了

**Comment by Timthony** [comment]
> 合成样本的时候，是可以计算出四边形顶点的坐标的，有了坐标，就可以在标签图上绘制边缘线了

谢谢回答，还有个问题就是在合成样本时我看sample文件夹里背景图片有208张，在ios模拟器合成的时候log出来的背景图片只有0/97张，最后生成的合成图invalid只有3万多张，是哪里出问题了吗，比如路径。

**Comment by Timthony** [comment]
> 合成样本的时候，是可以计算出四边形顶点的坐标的，有了坐标，就可以在标签图上绘制边缘线了

logs:
2018-11-20 21:01:06.253452+0800 generate_training_dataset[869:10656] documentsDirectory is: /Users/arcstone_mems_108/Library/Developer/CoreSimulator/Devices/EA1FA0AA-6981-4C15-A34D-89445CF6E171/data/Containers/Data/Application/59E990BC-69EF-4617-ADA0-C053C4DAEA83/Documents
# 2018-11-20 21:01:06.253610+0800 generate_training_dataset[869:10656] resourcePath is: /Users/arcstone_mems_108/Library/Developer/CoreSimulator/Devices/EA1FA0AA-6981-4C15-A34D-89445CF6E171/data/Containers/Bundle/Application/3465A461-4850-4887-BE1B-CB21FB442FEA/generate_training_dataset.app
# 2018-11-20 21:01:06.270228+0800 generate_training_dataset[869:10656] self.edgeImageView.layer.anchorPoint is: {0.5, 0.5}

**Comment by fengjian0106** [comment]
> > 合成样本的时候，是可以计算出四边形顶点的坐标的，有了坐标，就可以在标签图上绘制边缘线了
> 
> 谢谢回答，还有个问题就是在合成样本时我看sample文件夹里背景图片有208张，在ios模拟器合成的时候log出来的背景图片只有0/97张，最后生成的合成图invalid只有3万多张，是哪里出问题了吗，比如路径。

有些图片可能存在问题，或者格式不符合预期，会直接略过
