### ISSUE TITLE
请问怎么用opencv的dnn模块加载已经训练好的模型？

### ISSUE THREAD

**Issue by daltonxiong** [fengjian0106/hed-tutorial-for-document-scanning#26]
模型加载就失败了
```
import cv2

if __name__ == '__main__':
    net = cv2.dnn.readNet('hed_graph.pb')
```

报了下面这个错误
```
cv2.error: OpenCV(3.4.3) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:495: error: (-2:Unspecified error) Input layer not found: is_training in function 'connect'
```

[opencv官方的例子](https://github.com/opencv/opencv/blob/master/samples/dnn/edge_detection.py)也跑不起来。。。

**Comment by fengjian0106** [comment]
呃。。。这个我没试过。而且按照我个人的理解，也不应该太指望用 OpenCV 就能 "轻易的加载TensorFlow 的model"，因为 TensorFlow Lite 和 TensorFlow Mobile 支持的 operation 只是 TensorFlow 完整版的 operation 的子集，在 TensorFlow 官方的框架中，转换 Mobile 或 Lite 版模型文件的时候，都不能保证总是很顺利的一步到位得到想要的模型，第三方环境就更难做到这一点了。
OpenCV 所谓的支持 TensorFlow，估计也支持部分支持，也是一个子集，你如果还想尝试 OpenCV 的话，只能去 OpenCV 的源码和社区中找找线索了。
