### ISSUE TITLE
源码阅读

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#27]
一直想找时间阅读下您的代码，终于最近有空。发现看起代码好累，尤其在卷积操作这块，完全搞不懂为什么这么写，而且网上也试着搜寻了一些资料，想搞明白你是根据怎样的思路来构建此模型训练的代码。为此我查阅了相关知识点，例如cost function 、weight 、bias 、NN 、CNN 、convergence、 overfitting、MobileNet是基于CNN在移动设备上的另一种实现等知识点、还看过hed的文献。
最后还是云里雾里的，我的初衷是想通过此项目入门AI，但是看起代码来进展很慢。

**Comment by fengjian0106** [comment]
如果你是想入门AI的话，这份代码可能是显得稍微有一点难度了，我建议你从更基础的网络结构入手，比如最基本的DNN分类网络、CNN分类网络，先把分类任务搞明白，然后再扩充自己的知识储备，学习针对其他任务类型的网络结构。TensorFlow 官方文档其实就是一份很不错的入门教程，避开了一些晦涩的数学理论知识，直接从工程入手，等入门后，再查漏补缺，深入学习一些关键的技术点，完善自己的知识网络。

http://karpathy.github.io/neuralnets/   Hacker's guide to Neural Networks 这篇文章也是一个很不错的入门学习资料，用比较简单的数学知识对深度学习的关键技术做了一个很通俗的解释，可以啃一啃。

**Comment by weinixuehao** [comment]
谢谢！
