### ISSUE TITLE
filters 数目为

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#28]
![image](https://user-images.githubusercontent.com/17869361/49502066-47a8a500-f8af-11e8-9b9c-d7e4a615f723.png)
为什么filters 数目设置规律是翻倍的，3、6、12、24、48。在mobilenetv2论文里没有看到有关filter num问题

另外在这个图上
![image](https://user-images.githubusercontent.com/17869361/49502871-01544580-f8b1-11e8-8476-59fb81112b8a.png)
对比你的代码，好像只实现到这一层。
![image](https://user-images.githubusercontent.com/17869361/49502989-49736800-f8b1-11e8-8a40-aefca93bd6a4.png)

**Comment by fengjian0106** [comment]
1. 为什么filters 数目设置规律是翻倍的，3、6、12、24、48
这个其实就是一个经验值
2. 第二个问题
MobileNet V2 只是作为基础网络用来提取特征，然后再和 HED 网络对接上，为了"正确的对接"上，MobileNet 的 output 就需要和 HED 的 input 具有相同的 shape，按照这个思路，你在问题里提到的那一层，是一个相对最合适的层。这里是可以很灵活的使用的，比如做其他任务的时候，选择的 output 层可能又会有差异，我做 MobileNet V2 + SSD 或 YOLO V3 的时候，都是用这种思路选择最合适的层。

**Comment by weinixuehao** [comment]
你的博客上有描述参考Hed vgg style思路来的，请问这个地址多少？我没有搜索到。

**Comment by weinixuehao** [comment]
经验值？比如 2、4、8、16也是可以，最终以实际测试效果为准？效果不佳再从新调整？是否可以这么理解。可能问题比较傻，望理解。

**Comment by fengjian0106** [comment]
> 经验值？比如 2、4、8、16也是可以，最终以实际测试效果为准？效果不佳再从新调整？是否可以这么理解。可能问题比较傻，望理解。

可以近似这样理解吧

**Comment by fengjian0106** [comment]
> 你的博客上有描述参考Hed vgg style思路来的，请问这个地址多少？我没有搜索到。

http://fengjian0106.github.io/2017/05/08/Document-Scanning-With-TensorFlow-And-OpenCV/
