### ISSUE TITLE
您好，请问如何定量评价边缘检测结果

### ISSUE THREAD

**Issue by chaoyueziji** [fengjian0106/hed-tutorial-for-document-scanning#29]
您好，在进行边缘检测的时候，数据量过大的时候不能单凭借loss是否收敛来判断网络训练好吧，或者肉眼观察网络检测结果，请问，您在对模型进行训练的时候是如何定量评估网络训练结果的呢？

**Comment by fengjian0106** [comment]
你如果有人工标注的真实样本数据，就可以利用算法来评价，比如也可以用IOU来作为一个参考。我在工程中使用的时候，其实是肉眼观察分析的，即便神经网络部分的检测结果不够好，比如仍然检测出了很多干扰线段，但是在后续流程中的OpenCV算法也会再进一步的过滤，我的这个项目，追求的是最终的那个检测结果。

**Comment by chaoyueziji** [comment]
哈哈，好的，感谢这么及时的回答。
