### ISSUE TITLE
CSV format for annotations

### ISSUE THREAD

**Issue by BaptisteAmato** [fengjian0106/hed-tutorial-for-document-scanning#3]
Hi!
First, awesome work you did :)
I had already developed a way to generate data, and I would like to use your training algorithm, but I need to know what kind of format you use (like image_path, top-left corner, top-right corner, ...).
I currently use Pascal VOC format (for Yolo), is the needed csv format different?

**Comment by fengjian0106** [comment]
@BaptisteAmato HED is not a net to find corner (not like SSD or Yolo), so the output of HED is just an image matrix
