### ISSUE TITLE
模型部署

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#30]
![image](https://user-images.githubusercontent.com/17869361/50410934-29432300-0837-11e9-88ef-dbf0982baa50.png)
基于以上图片，有个疑问了。
ios_demo 里的hed_graph.pb是基于mobilenetv2 style hed训练的？
android要使用性能好的，是不是要改成vgg_style_hed的代码重新训练生成一个用于android的？

**Comment by weinixuehao** [comment]
补充：对照了你的vgg_hed_style 在做_vgg_conv2d操作的时候filter数目和hed caffe实现的数目不一致。
例如你的12 它的64，少这么多。是不是为了减少性能开销？性能开销减少的同时伴随着预测精度也降低了？

**Comment by fengjian0106** [comment]
> ![image](https://user-images.githubusercontent.com/17869361/50410934-29432300-0837-11e9-88ef-dbf0982baa50.png)
> 基于以上图片，有个疑问了。
> ios_demo 里的hed_graph.pb是基于mobilenetv2 style hed训练的？
> android要使用性能好的，是不是要改成vgg_style_hed的代码重新训练生成一个用于android的？

32bit的Android才用 vgg_style_hed 模型，这个是重新训练出来的，64bit的可以和iOS用一样的 mobilenetv2 style hed 模型。

**Comment by fengjian0106** [comment]
> 补充：对照了你的vgg_hed_style 在做_vgg_conv2d操作的时候filter数目和hed caffe实现的数目不一致。
> 例如你的12 它的64，少这么多。是不是为了减少性能开销？性能开销减少的同时伴随着预测精度也降低了？

filter的数量是调整过的，完整的HED网络挺大的，肯定要做一些修改才适合放到手机上。针对我的这个文档边缘检测任务，完整的HED和缩减过的HED，损失掉的精度并不是很大，是可以容忍的，就是在性能和精度之间找一个平衡点。

**Comment by weinixuehao** [comment]
你有试过BM3D filter吗？说是在去燥的同时，保持edge.

**Comment by fengjian0106** [comment]
> 你有试过BM3D filter吗？说是在去燥的同时，保持edge.

没试过
