### ISSUE TITLE
你们训练合成样本数是这么多么？还有训练了多少次？

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#31]
![image](https://user-images.githubusercontent.com/17869361/50757628-ed7a7580-129a-11e9-9c44-e40f044b5b90.png)
我已经训练了 35K 次数了，loss处于一个相对稳定阶段了。但实际测试不如作者提供的.pb。

**Comment by weinixuehao** [comment]
![Uploading image.png…]()
我改为vgg_style_hed 并去掉了batch_norm
样本就是基于上面的那些合成的，图片都是项目里，没有新增样本。

**Comment by fengjian0106** [comment]
我就是用的 sample_images 目录里的图片来生成的样本

**Comment by weinixuehao** [comment]
跑了一晚上 有90k了感觉效果接近，你提供的pb效果了。请问你跑了多少次结束的？

**Comment by fengjian0106** [comment]
我不记得具体跑了多少次了，我用 iMac 的 cpu 训练，一般也就是跑一两天
