### ISSUE TITLE
Android 输出的图像怎么是这样的呢？求教，上图是输入的图片256x256，下图是输出

### ISSUE THREAD

**Issue by cheshenghui** [fengjian0106/hed-tutorial-for-document-scanning#32]
![71e72ca6-5866-4be0-8a49-1a2e74641db5](https://user-images.githubusercontent.com/7794016/50823603-50d5d780-136f-11e9-95f9-f5260f9591ae.png)

**Comment by fengjian0106** [comment]
输出的不是256*256的image 了吗？
神经网络输出的矩阵，肯定还是256*256的，然后转换成opencv的mat才能做后续的处理和显示，估计是你的opencv部分出错了

**Comment by cheshenghui** [comment]
我用的是给Android提供的JavaAPI，不是c++API，代码这样的：
        TensorFlowInferenceInterface inferenceInterface
                = new TensorFlowInferenceInterface(context.getAssets(), PB_FILE_PATH);
        // shape(1,256,256,3)
        inferenceInterface.feed(INPUT_NODE, bitmap2FloatArray(srcCroppedBitmap), 1, 256, 256, 3); 
        inferenceInterface.feed(IS_TRAINING, new boolean[]{false});  // is_training false
        inferenceInterface.run(new String[]{OUTPUT_NODE}, true);
        inferenceInterface.fetch(OUTPUT_NODE, outputFloatArray); // 返回的是float数组，转为bitmap就成那样了，不知道为什么

**Comment by fengjian0106** [comment]
呃。。。这个问题的原因，肯定是 raw image data 的格式没有匹配上。你应该先检查你的 input image 转换成 tensorflow 的 input tensor 的时候，tensor 的格式是否符合 net model 的要求，然后再检查 tensorflow 的 output tensor 是否有正确的转换为 image，只能去查文档一点一点调试了。

**Comment by yimiwangzi** [comment]
> 我用的是给Android提供的JavaAPI，不是c++API，代码这样的：
> TensorFlowInferenceInterface inferenceInterface
> = new TensorFlowInferenceInterface(context.getAssets(), PB_FILE_PATH);
> // shape(1,256,256,3)
> inferenceInterface.feed(INPUT_NODE, bitmap2FloatArray(srcCroppedBitmap), 1, 256, 256, 3);
> inferenceInterface.feed(IS_TRAINING, new boolean[]{false}); // is_training false
> inferenceInterface.run(new String[]{OUTPUT_NODE}, true);
> inferenceInterface.fetch(OUTPUT_NODE, outputFloatArray); // 返回的是float数组，转为bitmap就成那样了，不知道为什么

请问你的函数bitmap2FloatArray是如何实现的，我是这样做的，输出的图片不对
  // 获得图片的宽高
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();
        // 设置想要的大小
        int newWidth = 256;
        int newHeight = 256;
        // 计算缩放比例
        float scaleWidth = ((float) newWidth) / width;
        float scaleHeight = ((float) newHeight) / height;
        // 取得想要缩放的matrix参数
        Matrix matrix = new Matrix();
        matrix.postScale(scaleWidth, scaleHeight);
        // 得到新的图片
        Bitmap newbm = Bitmap.createBitmap(bitmap, 0, 0, width, height, matrix,
                true);
        int w=newbm.getWidth();
        int h=newbm.getHeight();
        float[] floatValues = new float[w*h*3];
        int[]   intValues=new int[w*h];
        newbm.getPixels(intValues,0,newbm.getWidth(),0,0,newbm.getWidth(),newbm.getHeight());
        float imageMean = 128.0f;
        float imageStd =  128.0f;
        for (int i=0;i<intValues.length;i++){
            final int val= intValues[i];
            floatValues[i * 3 + 0] = (((val >> 16) & 0xFF) -imageMean) /imageStd;
            floatValues[i * 3 + 1] = (((val >> 8) & 0xFF)-imageMean)/imageStd ;
            floatValues[i * 3 + 2] = ((val & 0xFF)- imageMean) /imageStd ;
        }
        return floatValues;

**Comment by amarsaikhanb** [comment]
Hi @fengjian0106 @cheshenghui @yimiwangzi 
Please see the following code.
The returned output float array is the same as the input array. What should I do?
```
    private final String modelName = "hed_graph.pb";
    private final String inputName = "hed_input";
    private final String outputName = "hed/dsn_fuse/conv2d/BiasAdd";
    private final String isTrainingName = "is_training";
    private int inputSize = 256;
    private float[] inputFloats;
    private float[] outputs;
    private String[] outputNames = new String[]{outputName};
    private boolean[] trainings = new boolean[]{false};

    public float[] run(Mat frame) {
        frame = Imgproc.resize(frame, frame, new Size(inputSize, inputSize));

        inputFloats = new float[ frame.rows() * frame.cols() * 3 ];

        frame.convertTo(frame, CvType.CV_32F);
        frame.get(0,0, inputFloats);


        //It's no training
        inferenceInterface.feed(isTrainingName, trainings);

        // Copy the input data into TensorFlow.
        inferenceInterface.feed(inputName, inputFloats, 1, inputSize, inputSize, 3);

        // Run the inference call.
        inferenceInterface.run(outputNames, logStats);

        // Copy the output Tensor back into the output array.
        inferenceInterface.fetch(outputName, outputs);
        //Log.e("OUTPUT", " "+outputs);
        return outputs;
        
    }
```
