### ISSUE TITLE
vgg_hed_style ios测试输出全黑

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#33]
![74b74b502915fa797bcbdfa3317b562d](https://user-images.githubusercontent.com/17869361/50888859-8642f980-1431-11e9-8f1a-b5aa0d67108f.png)
这个是通过evaluate_hed.py 输出的结果
![hedoutputimage](https://user-images.githubusercontent.com/17869361/50888925-aa9ed600-1431-11e9-8ca2-9cc7ea2753df.jpg)
这个是手机上输出的结果
![image](https://user-images.githubusercontent.com/17869361/50889010-d91cb100-1431-11e9-9926-1bba19a85a9b.png)
代码只改了这一处，因为改为vgg_hed_style 去掉bash_norm后，传is_training 出错。
错误日志：tf_session->Run error: FeedInputs: unable to find feed output is_training:0
所以去掉了is_training.

**Comment by fengjian0106** [comment]
vgg style 的时候，OpenCV 部分的代码还需要修改，这部分我没有做成可以用开关变量直接切换的方式，只是在 https://github.com/fengjian0106/hed-tutorial-for-document-scanning/blob/master/ios_demo/DemoWithStaticLib/DemoWithStaticLib/ViewController.mm 里面简单注释了一下，你可以在这个 ViewController.mm 里搜索 "vgg"，看一下相关的内容。因为 vgg hed net 的 input 和 output 跟 mobilenet hed net 的并不一致，所以要另外处理
