### ISSUE TITLE
手机 pc识别效果不一致

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#34]
![debug_55](https://user-images.githubusercontent.com/17869361/50949511-7a167500-14e1-11e9-83a7-7c8916a8a2c8.jpg)
这个是手机的识别会断线
![image](https://user-images.githubusercontent.com/17869361/50949551-a16d4200-14e1-11e9-9c1a-99f9abfc1a5a.png)
这个是用evaluate_hed.py 识别的就不会断线

**Comment by fengjian0106** [comment]
神经网络输出的矩阵是一样的，在转换成opencv mat的时候，还用了一个 threshold 参数，py版和Objcectivie-C版本可能有一些差异，所以出现了断线。我的python版本只是用来做前期开发和简单验证的，实际产品中我用的手机版代码，opencv部分的调优都是在手机版代码中做的。

**Comment by weinixuehao** [comment]
也就是可以通过调优，使这个断线的情况，变成和python版本一样不断线。

**Comment by fengjian0106** [comment]
> 也就是可以通过调优，使这个断线的情况，变成和python版本一样不断线。

理论上是这样的。但是是否有断线，只是一个因素，还要考虑检测出来的线的宽度、其他的干扰线段等等。比如，opencv部分的算法对于断线是有一定的容忍度的。

**Comment by ljdang** [comment]
对图片压缩到256*256的时候，手机端和PC端的压缩方式不同，导致最后出来的边缘效果也稍微有所不同，手机端的干扰会多点。
