### ISSUE TITLE
矩形 已知3点位置求第4点位置

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#35]
矩形已知三点求第4点位置，有试过没？应该很好求吧。
![image](https://user-images.githubusercontent.com/17869361/50956880-cec4ea80-14f7-11e9-8679-4417a9e29963.png)

**Comment by fengjian0106** [comment]
理论上是可以求，第4个点也可能本身就是被遮盖物挡住的一个角，本来就是不可见的。
