### ISSUE TITLE
请问下作者提供的权重是训练了多少次

### ISSUE THREAD

**Issue by chaoyueziji** [fengjian0106/hed-tutorial-for-document-scanning#36]
不好意思，冒昧问题您提供的权重只训练了130步嘛。。

**Comment by chaoyueziji** [comment]
主要是我现在训练了近几万步都没您提供的效果好，所以。。。

**Comment by fengjian0106** [comment]
具体多少步我也记不清楚了，我用iMac的CPU训练的，在我自己的电脑上训练一天多就够了

**Comment by chaoyueziji** [comment]
只要不是130步就行。。。。主要是我训练了好一阵都没有您开源权重那么高，有点慌。。。感谢了
