### ISSUE TITLE
咨询几个问题

### ISSUE THREAD

**Issue by dugufly** [fengjian0106/hed-tutorial-for-document-scanning#37]
1. Android上的性能数据是基于哪个手机？
2. 改成vgg_style_hed， 正确率有没有变化？ 这个网络的模型尺寸是多大？
3. 你博文中提到模型尺寸从4.4M降到1.6M，是什么原因？
4. Android中QQ邮箱的“扫描文件”功能，跟这个算法是一样的么？

**Comment by fengjian0106** [comment]
1. 具体是哪款Android机型我记不清楚了，应该是一款中端机型。
2. 在我的应用场景中，vgg_style_hed 和 mobilenet_v2_style_hed 的最终效果差别并不算大。
3. mobilenet v1 和 v2，追求的就是尽量小的模型size，同时保持尽量高的准确率，你可以仔细对比 vgg 和 mobilenet 的内部网络结构，看看差别。
4 在iOS和Android上部署的时候，还增加了其他的一些策略，会检测硬件配置信息，如果性能比较低的机型，就不会使用这个算法，而是使用纯OpenCV实现的一套旧版本算法。
