### ISSUE TITLE
合成数据

### ISSUE THREAD

**Issue by 154461013** [fengjian0106/hed-tutorial-for-document-scanning#38]
2.2 将 2.1 里面生成的图片，全部移动到 ./dataset/generate_sample_by_ios_image_size_256_256_thickness_0.2 目录里。
我不懂object_c，目前在学习训练模型，合成的图片能不能发给我邮箱一下154461013@qq.com
或者能不能把合成图片的原理说一下，为什么要用Iphone模拟器合成

**Comment by fengjian0106** [comment]
合成的图片的数量很大，邮箱不可能发送的了的。
http://fengjian0106.github.io/2017/05/08/Document-Scanning-With-TensorFlow-And-OpenCV/  这个第一篇博客有解释原理和原因，用 iPhone 其实就是为了使用OpenGL来合成，而不是在Python中使用OpenCV。

一张背景图和一张前景图，可以合成出一对训练样本数据。在合成图片的过程中，用到了下面这些技术和技巧：

1. 在前景图上添加旋转、平移、透视变换
2. 对背景图进行了随机的裁剪
3. 通过试验对比，生成合适宽度的边缘线
4. OpenCV 不支持透明图层之间的旋转和透视变换操作，只能使用最低精度的插值算法，为了改善这一点，后续改成了使用 iOS 模拟器，通过 CALayer 上的操作来合成图片
5. 在不断改进训练样本的过程中，还根据真实样本图片的统计情况和各种途径的反馈信息，刻意模拟了一些更复杂的样本场景，比如凌乱的背景环境、直线边缘干扰等等
