### ISSUE TITLE
自定义训练图片

### ISSUE THREAD

**Issue by 154461013** [fengjian0106/hed-tutorial-for-document-scanning#39]
楼主能帮我理解一下样本标签吗，HED网络检测边缘线，理论上来说是对边缘位置处的像素做像素级的分类。
特定场景识别矩形，自己标注图片，是不是只标注待识别的矩形框，比如
![image](https://user-images.githubusercontent.com/45627764/51957331-367ead80-2486-11e9-8b3e-1cace0f29e30.png)
是不是只要标注成类似这样？
![image](https://user-images.githubusercontent.com/45627764/51957377-63cb5b80-2486-11e9-9062-efde8a03eb2d.png)
其他的边缘都不需要，还是要把其他的边缘也标注出来？
把想要的边缘作为标签输入，去训练。自己合成图片是不是也是这样的。原图的边缘，记录位置，经过变化以后，计算出对应的边缘位置，作为训练标签。

**Comment by fengjian0106** [comment]
是的，只标注待识别的矩形框。
合成样本的时候，就是记录原图的4个顶点的位置，然后做了透视变换、旋转变换后，计算出4个顶点的新的位置，连接成一个四边形就行了
