### ISSUE TITLE
Base code - C/C++

### ISSUE THREAD

**Issue by BaptisteAmato** [fengjian0106/hed-tutorial-for-document-scanning#4]
Hi :)
I would like to use this code to return the coordinates of the four corners; how can I do that? 
With the Python instructions given in the README, I only get the resulting image, not the corners :s

**Comment by fengjian0106** [comment]
hi, @BaptisteAmato , the Python code just run HED net, and return an Image matrix.  The [C++ code](https://github.com/fengjian0106/hed-tutorial-for-document-scanning/blob/master/ios_demo/FMHEDNet/FMHEDNet/fm_ocr_scanner.hpp) will find the four corners,  you can run ios_demo and see. the algorithm to find corners is base on OpenCV, and I did not implement a python version

**Comment by BaptisteAmato** [comment]
I see, thanks a lot :)
