### ISSUE TITLE
样本制作思路

### ISSUE THREAD

**Issue by 154461013** [fengjian0106/hed-tutorial-for-document-scanning#40]
我有个制作样本的想法，把nyud_cropped做语义分割的样本，通过对训练样本做canny识别，成这样
![image](https://user-images.githubusercontent.com/45627764/52040458-67d4a780-2572-11e9-8f00-9259c3242d13.png)
![image](https://user-images.githubusercontent.com/45627764/52040466-6dca8880-2572-11e9-82e3-af4522c99cd5.png)

这样就有几万样本，来训练，不知道是否可行，因为原先是整体类别作为一类，所以有的边缘canny检测不出来，这样做样本 是否能对模型有提升，楼主觉得可行吗

**Comment by fengjian0106** [comment]
你的最终目标是什么？是检测边缘，还是说就是要做语义分割？

**Comment by 154461013** [comment]
识别图片中的一个矩形物体边缘，边缘会有水打湿，光照暗等干扰，HED检测出来比较粗，想多找点样本

**Comment by fengjian0106** [comment]
样本要有针对性才行，你的检测目标始终都是矩形物体吗？如果是，你的样本就应该尽量都是矩形物体。
前面你举例时用的nyud_cropped的那个样本图片，就不太合适，因为里面有很多杂物，他们的边缘都被画出来了。
另外，顺便说一下，HED不一定就是最合适的选择，其实我也用语义分割网络尝试过检测文档的边缘，用语义分割网络时，检测到的边缘线是很细的，比HED好很多，但是断线的情况也更明显，我估计可能和样本图片的质量有关系，毕竟我的是合成的假图片，绘制出来的边缘线和真实的边缘线不一定就是完美重合的，如果能够人工标注边缘线，用语义分割网络可能就能做到更好的效果。
