### ISSUE TITLE
关于运行环境

### ISSUE THREAD

**Issue by tuqiangwang** [fengjian0106/hed-tutorial-for-document-scanning#41]
1、TensorFlow版本是多少
2、OpenCV需要吗
你们训练、测试环境都没讲清楚啊

**Comment by tuqiangwang** [comment]
TensorFlow0.11.0 
python2.7
可用

**Comment by fengjian0106** [comment]
train_hed.py 里面有下面这段代码

import tensorflow as tf
from distutils.version import LooseVersion
assert LooseVersion(tf.__version__) >= LooseVersion('1.6'), 'Please use TensorFlow version 1.6 or newer'
print('TensorFlow Version: {}'.format(tf.__version__))
