### ISSUE TITLE
Compile DemoWithStaticLib Failed

### ISSUE THREAD

**Issue by liangyanfeng** [fengjian0106/hed-tutorial-for-document-scanning#43]
FrameworkAndLib/FMHEDNet/libFMHEDNet.a (3 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FMHEDNet", referenced from:
      objc-class-ref in ViewController.o
  "ProcessEdgeImage(cv::Mat, cv::Mat, bool)", referenced from:
      -[ViewController processImage:] in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fengjian0106** [comment]
FMHEDNet需要把模拟器版本编译出来才行，你试一下

**Comment by Mysterious0o0** [comment]
> FMHEDNet需要把模拟器版本编译出来才行，你试一下

麻烦问一下，模拟器版本编译是什么意思，之前都是用windows的，麻烦帮我解答一下谢谢

**Comment by fengjian0106** [comment]
> > FMHEDNet需要把模拟器版本编译出来才行，你试一下
> 
> 麻烦问一下，模拟器版本编译是什么意思，之前都是用windows的，麻烦帮我解答一下谢谢

这份代码是针对iOS平台的，要用macos上的xcode编译，同时，xcode里面也有iPhone的模拟器，前面报的编译错误里面有 "not found for architecture x86_64" 这个信息，说明是用的模拟器
