### ISSUE TITLE
现在支持tensoflower lite android 部署了吗？

### ISSUE THREAD

**Issue by fangxu622** [fengjian0106/hed-tutorial-for-document-scanning#45]
https://www.tensorflow.org/lite/guide/ops_compatibility#unsupported_operations

现在好像支持 transpose_conv 操作了吧？

**Comment by dustturtle** [comment]
理论上应该可行吧？ 有没有实践

**Comment by fengjian0106** [comment]
目前还没做这个尝试

**Comment by weinixuehao** [comment]
@fengjian0106 @dustturtle 
你们有遇到过pb to tflite 后精度大幅下降？

**Comment by dustturtle** [comment]
@weinixuehao  我的业务里没使用这个，因为感觉自己标注比较困难。 你是自己训练的模型吗？ 合成的样本？

**Comment by weinixuehao** [comment]
@dustturtle 基于作者的，感觉精度有所损失。相对于pc端做测试。

**Comment by fengjian0106** [comment]
@weinixuehao 如果tflite损失的精度比较大，你可以考虑在转化tflite model的时候，不要quantization

**Comment by weinixuehao** [comment]
@fengjian0106 默认设置是quantization?

**Comment by dustturtle** [comment]
默认应该是不量化的，你可以把量化用的脚本贴出来看看 @weinixuehao

**Comment by weinixuehao** [comment]
@dustturtle 我是没量化的，其实我试了下，tf_doc_localisation这个基于heatmap的。作者是用的600x800效果还行，当我缩放到224x244进行训练精度有下降，但在pc还是可以进行预测，手机端就很糟糕了，600x800其实转后也会下降，但是在手机端还是可以预测。

**Comment by weinixuehao** [comment]
@fengjian0106 @dustturtle 
今天试了下转tensorflow-lite model 报错
![image](https://user-images.githubusercontent.com/17869361/58788198-ebd09600-861d-11e9-8c03-1bad36b53018.png)
ValueError: Unsupported tf.dtype <dtype: 'bool'>
is_training_placeholder 这个是bool tensor
是否需要重新修改代码，重新训练？

**Comment by fengjian0106** [comment]
tflite输出的tensor，你是怎样判断它的精度下降的？转成opencv的mat后，绘制出来，肉眼判断的吗？ @weinixuehao

**Comment by weinixuehao** [comment]
肉眼 不过是tf_doc_localisation项目完全识别不了。请忽略[tf_doc_localisation]。往下看。


现在我遇到的问题，是你的项目在转tflite model报以下错
![image](https://user-images.githubusercontent.com/17869361/58869173-4b977180-86f0-11e9-9767-82a488a1c28a.png)
is_training_placeholder 这个不能是用于batch_normal的，不知道怎么改，规避这个bool tensor的使用
@fengjian0106

**Comment by fengjian0106** [comment]
@weinixuehao 
呃。。。应该是有办法可以绕开这个问题。
https://github.com/tensorflow/tensorflow/issues/24477

The TFLite converter expects an eval graph as input. This means a graph where all calls to batch norm are created with is_training=False.

So, you traing a float model with is_training=True and create_training_graph. Save the checkpoint.
Then you build the same model with is_training=False and create_eval_graph. This is the graph that the Tfliteconverter expects.

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/58884105-4e0ac300-8712-11e9-940f-4ac2beb0419b.png)
这个tensor 在转tflite的时候去掉？默认为false?
![image](https://user-images.githubusercontent.com/17869361/58884154-6aa6fb00-8712-11e9-8668-9e2a30eeb9de.png)

**Comment by fengjian0106** [comment]
> ![image](https://user-images.githubusercontent.com/17869361/58884105-4e0ac300-8712-11e9-940f-4ac2beb0419b.png)
> 这个tensor 在转tflite的时候去掉？默认为false?
> ![image](https://user-images.githubusercontent.com/17869361/58884154-6aa6fb00-8712-11e9-8668-9e2a30eeb9de.png)

1. 用原来的代码流程训练模型，2. 在导出模型的时候，修改代码，彻底去掉 is_training_placeholder 这个 input 变量，在 batch norm 部分固定设置上 is_training=False，3. 把第二步导出的模型，转换成 tflite 模型

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/59003243-af807e00-8847-11e9-87fa-dfc7bcbea891.png)
这个是tensorflow-lite的
![image](https://user-images.githubusercontent.com/17869361/59003272-ca52f280-8847-11e9-8e60-bcbe02f1f7c9.png)
这个是python eval 脚本的。
效果还行，到时试试量化的。

**Comment by fengjian0106** [comment]
嗯，这个效果看上去已经不错了，这个tflite模型的size是多少呢？运行速度如何？

**Comment by weinixuehao** [comment]
用之前的方式在android上测试是，700多ms。
lite部署方式是200多ms，lite看试试优化能不能在下降到100ms就爽了。
之前是1.6m 现在是1.1m @fengjian0106 
量化只试过post-training(Quantization-aware training要重新改代码，在训练还没试过)。时间反而增加了针对于mobile-net,但是模型质量只有363kb了。
使用了gpu加速模型速度降到180ms左右了。

**Comment by amarsaikhanb** [comment]
Hi @fengjian0106 @weinixuehao 
.pb to .tflite created issue
`          converter = lite.TFLiteConverter.from_session(sess, [image_float], [dsn_fuse])
            converter.allow_custom_ops=True                
            tflite_model = converter.convert()
            open("model.tflite","wb").write(tflite_model)
            print("TFlite convert finished")`
error:
`  File "/home/users/.local/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: TensorFlow Lite currently doesn't support control flow ops: Merge, Switch.`
![image](https://user-images.githubusercontent.com/28631770/62763697-c39e6100-babe-11e9-9152-14bf038d37e5.png)

![image](https://user-images.githubusercontent.com/28631770/62763645-aa95b000-babe-11e9-8149-0b864964546b.png)
How to convert sess to tflite ? @weinixuehao
