### ISSUE TITLE
关于标注工具

### ISSUE THREAD

**Issue by dustturtle** [fengjian0106/hed-tutorial-for-document-scanning#46]
你好，想请问下文章中所说的标注工具，是否有开放出来，感谢！

**Comment by fengjian0106** [comment]
这个标注工具只是很简单的内部工具，缺少长期维护，而且耦合了一些其他的业务模块，没有开放的计划。
另外，这个模型的训练，其实主要还是依靠的生成出来的那批样本的。如果你有自己的真实样本标注需求，完全可以做一个标注的小工具。
