### ISSUE TITLE
mat和数组的相互转化

### ISSUE THREAD

**Issue by yimiwangzi** [fengjian0106/hed-tutorial-for-document-scanning#48]
求教java种Mat如何转为float数组的啊，float数组又是如何转mat的啊，
我试了下纯opencv检测文档时，视频卡的不要不要的你们怎么处理的

**Comment by fengjian0106** [comment]
TensorFlow的官方demo、tutorial、文档中，应该是可以找到你期望的答案的。我做iOS版时，C++的tensor变量和OpenCV 的 Mat 矩阵的互相转换，也是在官方 demo code 中找到的线索
