### ISSUE TITLE
项目License

### ISSUE THREAD

**Issue by heromanba** [fengjian0106/hed-tutorial-for-document-scanning#49]
作者你好，请问可以给这个项目添加一个License吗？因为感觉Github上默认copyright还挺严格的。
![license](https://user-images.githubusercontent.com/22102769/56937375-d48a1e80-6b2e-11e9-983b-526c2499a82d.JPG)

**Comment by fengjian0106** [comment]
这个项目的目的，更偏向于一个教程性质的demo，没有太在意 License 这方面的问题，可以直接使用。
