### ISSUE TITLE
判断延长线是否相等会漏掉很多接近平行或垂直的线段

### ISSUE THREAD

**Issue by wenyafei4** [fengjian0106/hed-tutorial-for-document-scanning#5]
hello,关于后处理的如下逻辑想跟您探讨下，不知道理解的是否正确。
![image](https://user-images.githubusercontent.com/11274308/41716417-ede41378-7588-11e8-9769-2ead423687b0.png)

**Comment by fengjian0106** [comment]
@wenyafei4 
在 static RefLineVec4i GetRefLine(const cv::Vec4i line, int image_width, int image_height) 这个函数里面，有两个分支就是处理和 X 轴或 Y 轴平行的延长线的。
另外，即便在过滤 RefLineVec4i 的时候出现了遗漏，在后面寻找segment线段的交叉点的时候，还会有进一步的过滤。
