### ISSUE TITLE
image enhencement

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#50]
我发现这篇文章：https://blogs.dropbox.com/tech/2016/08/fast-document-rectification-and-enhancement/#disqus_thread
但是不知道怎么求解Poisson’s equation 用conjugate gradient descent。
网上搜索了大量资料，没有一个类似的demo。
请问你知道么？

**Comment by fengjian0106** [comment]
不太清楚这个
