### ISSUE TITLE
获取到边缘图像后的后处理问题

### ISSUE THREAD

**Issue by mayidu** [fengjian0106/hed-tutorial-for-document-scanning#52]
您好，我在python的环境下，采用evaluate.py得到了hed边缘检测的二值化图像，目前得到的图像shape是（256,256,1），但是在进行后处理的时候一直报错，如何将得到的图像得到MAT类呢，谢谢！

**Comment by fengjian0106** [comment]
错误信息是什么？另外，你要用什么库进行后续的处理，应该先确定你的后续流程需要什么格式的mat或者numpy array，然后再对照格式转换过去就行

**Comment by mayidu** [comment]
错误信息牵扯到后续的出来步骤，我是想得到一个numpy array，但是网络输出得到的图不是个numpy的，我如果把图像报错下来，在用cv2去读取就可以，但是问题是想解决如果对生成的图像进行转换得到一个numpy array，或者说得到的图是什么类型的，我一直转换不过去

**Comment by fengjian0106** [comment]
"想得到一个numpy array，但是网络输出得到的图不是个numpy的"

这个问题，其实很容易 Google 到结果的，
https://stackoverflow.com/questions/34097281/how-can-i-convert-a-tensor-into-a-numpy-array-in-tensorflow
"Any tensor returned by Session.run or eval is a NumPy array"

**Comment by mayidu** [comment]
嗯，非常感谢回复，可能我的表述不是很清楚，不是这一块的问题吧，不过目前这个不是最主要的，我更想了解一下你的后处理的思路，有没有python版本的后处理代码能分享一下，感谢！

**Comment by fengjian0106** [comment]
没有python版的opencv部分算法，C++版本的在 https://github.com/fengjian0106/hed-tutorial-for-document-scanning/blob/master/ios_demo/FMHEDNet/FMHEDNet/fm_ocr_scanner.cpp 这里，可以参考，然后改写成python版的

**Comment by mayidu** [comment]
好的，非常感谢，我学习学习！

**Comment by mayidu** [comment]
您好,我现在把后处理部分的代码转为python的，进行测试了一下，在我的数据中，有四分三的图像会出现如下结果：
![image](https://user-images.githubusercontent.com/29938271/58693571-a44ecd80-83c3-11e9-9aa3-44abf3a40a3a.png)
其corners输出的结果为：
![image](https://user-images.githubusercontent.com/29938271/58693600-b892ca80-83c3-11e9-97da-52166ad507d9.png)

hed网络输出的结果也是不错的，代码里面的参数也没有修改，但是却出现了很多这样的异常情况，是什么原因呢，还是在转换的时候有的没有转换对，您能帮忙看看吗，感谢！

**Comment by fengjian0106** [comment]
你写的python算法，跟我的C++版本的算法是完全一样的吗？C++算法里面，有很多过滤策略的，会尽量的把不合理的corners过滤掉，对检测到的线段也会做很多处理，比如适当的延长、合并等等，最终的效果，是多种策略组合出来的。你这个测试场景，其实是很简单的背景和前景，C++版本的算法，是可以处理好这种场景的。

**Comment by mayidu** [comment]
[嗯，是的，我是完全按照你的那个c++的代码转的，也有可能是里面有些函数在转换的过程中出现错误了吧，我可以把这个代码发给你，你帮我看看也可以


###代码
##!/usr/env/bin python3
#encoding=utf-8

import cv2
import os
import numpy as np
import math

#定义一些参数
kHoughLinesPThreshold = 20
kHoughLinesPMinLinLength = 20.0
kHoughLinesPMaxLineGap = 3.0

kMergeLinesMaxDistance = 5
kIntersectionMinAngle = 45
kIntersectionMaxAngle = 135
kCloserPointMaxDistance = 6.0
kRectOpposingSidesMinRatio = 0.5
kPointOnLineMaxOffset = 8
kSameSegmentsMaxAngle = 5


def GetRefLine(line, image_width, image_height):
    #ref_line = line
    ref_line = []
    if (line[0] == line[2]):
        #ref_line[0] = line[0]
        #ref_line[1] = 0
        #ref_line[2] = line[2]
        #ref_line[3] = image_height
        ref_line.append(line[0])
        ref_line.append(0)
        ref_line.append(line[2])
        ref_line.append(image_height)
    elif (line[1] == line[3]):
        #ref_line[0] = 0
        #ref_line[1] = line[1]
        #ref_line[2] = image_width
        #ref_line[3] = line[3]
        ref_line.append(0)
        ref_line.append(line[1])
        ref_line.append(image_width)
        ref_line.append(line[3])
    
    else:
        a = float((line[1] - line[3])) / float(line[0] - line[2])
        b = float(line[0]*line[3] - line[2]*line[1]) / float(line[0] - line[2])
        
        #ref_line[0] = 0
        #ref_line[1] = int(b)
        #ref_line[2] = int((image_height - b) / a)
        #ref_line[3] = image_height
        ref_line.append(0)
        ref_line.append(int(b))
        ref_line.append(int((image_height - b) / a))
        ref_line.append(image_height)
    return ref_line

def IsTwoRefLineCloseToEachOther(line_a, line_b):
    if (abs(line_a[1] - line_b[1]) < kMergeLinesMaxDistance and abs(line_a[3] - line_b[3]) < kMergeLinesMaxDistance):
        return True
    else:
        return False

def GetSegmentIntersection(line1, line2):
    xdiff = (line1[0] - line1[2], line2[0] - line2[2])
    ydiff = (line1[1] - line1[3], line2[1] - line2[3])

    def det(a, b):
        return a[0] * b[1] - a[1] * b[0]

    div = det(xdiff, ydiff)
    if div == 0:
       #raise Exception('lines do not intersect')
       return None

    #d = (det(*line1), det(*line2))
    d = (det(*[[line1[0], line1[1]], [line1[2], line1[3]]]), det(*[[line2[0], line2[1]], [line2[2], line2[3]]]))
    x = det(d, xdiff) / div
    y = det(d, ydiff) / div
    return (x, y)

def GetAngleOfLine(line):
    x1, y1, x2, y2 = line
    
    angle = math.atan2(y2 - y1, x2 - x1) * 180.0/np.pi
    fix_angle = (int(angle) + 360) % 360
    if fix_angle >= 360:
        fix_angle = 360
    elif fix_angle <= 0:
        fix_angle = 0
    return fix_angle

def MergeRefLineAndSegmentPairs(ref_line_and_segment_pairs, image_width, image_height):
    """
       HoughLinesP检测出来的是线段，是有长度的。
       把每一个线段扩展成一个统一规格的 RefLineVec4i，形成一个 pair，然后调用这个函数，对这些 pair 进行合并。
       用RefLineVec4i来决策是否需要合并，对于需要合并的，则把对应的HoughLinesP线段重组成一个更长的线段。
    """
    merged_ref_line_and_segment_pairs = []
    for i in range(len(ref_line_and_segment_pairs)):
        ref_line_and_segment = ref_line_and_segment_pairs[i]
        ref_line, segment = ref_line_and_segment
        
        if len(merged_ref_line_and_segment_pairs) == 0:
            merged_ref_line_and_segment_pairs.append([ref_line, segment])
        else:
            isCloser = False
            #print('merged_ref_line_and_segment_pairs',merged_ref_line_and_segment_pairs)
            for j in range(len(merged_ref_line_and_segment_pairs)):
                merged_ref_line_and_segment = merged_ref_line_and_segment_pairs[j]
                #print('merged_ref_line_and_segment',merged_ref_line_and_segment)
                merged_ref_line = merged_ref_line_and_segment[0]
                merged_segment = merged_ref_line_and_segment[1]
                
                if (IsTwoRefLineCloseToEachOther(ref_line, merged_ref_line)):
                    #如果两条ref line很接近， 则把两个segment合并成一个， 然后重新生成ref line
                    #先取出4个点
                    p0 = (segment[0], segment[1])
                    p1 = (segment[2], segment[3])
                    p2 = (merged_segment[0], merged_segment[1])
                    p3 = (merged_segment[2], merged_segment[3])
                    
                    point_list = []
                    point_list.append(p0)
                    point_list.append(p1)
                    point_list.append(p2)
                    point_list.append(p3)
                    
                    #以x轴的大小对四个点进行排序
                    point_list = sorted(point_list,key=lambda x:x[0])
                    #排序之后，得到最左边和最右边的两个point， 这两个point就构成新的线段
                    
                    left_most_point = point_list[0]
                    right_most_point = point_list[3]
                    
                    new_segment = segment
                    new_segment[0] = left_most_point[0]
                    new_segment[1] = left_most_point[1]
                    new_segment[2] = right_most_point[0]
                    new_segment[3] = right_most_point[1]
                    
                    new_ref_line = GetRefLine(new_segment, image_width, image_height)
                    merged_ref_line_and_segment_pairs[j] = [new_ref_line, new_segment]
                    isCloser = True
            if (isCloser == False):
                merged_ref_line_and_segment_pairs.append([ref_line, segment])
    return merged_ref_line_and_segment_pairs

def ArrangeRectCorners(rect_corners):
    """
    按照顺时针排序，对4个 corner 排序，得到 4 corners: top-left, top-right, bottom-right, bottom-left, index are 0, 1, 2, 3
    """
    sorted_corners = []
    if len(rect_corners) == 4:
        rect_corners = sorted(rect_corners, key=lambda x:x[0][0])
        
        left_two_corners = []
        right_two_corners = []
        left_two_corners.append(rect_corners[0])
        left_two_corners.append(rect_corners[1])
        right_two_corners.append(rect_corners[2])
        right_two_corners.append(rect_corners[3])
        
        left_two_corners = sorted(left_two_corners, key=lambda x:x[0][1])
        right_two_corners = sorted(right_two_corners, key=lambda x:x[0][1])
        
        #top-left, top-right, bottom-right, bottom-left
        sorted_corners.append(left_two_corners[0])
        sorted_corners.append(right_two_corners[0])
        sorted_corners.append(right_two_corners[1])
        sorted_corners.append(left_two_corners[1])
    return sorted_corners

def IsSegmentsHasSameSegment(segments, segment, image_width):
    for i in range(len(segments)):
        seg = segments[i]
        
        angle_a = int(GetAngleOfLine(seg))
        angle_b = int(GetAngleOfLine(segment))
        
        diff = int(abs(angle_a - angle_b))
        diff = diff % 90
        if diff < kSameSegmentsMaxAngle or diff > (90 - kSameSegmentsMaxAngle):
            return True
        else:
            return False

def PointsDistance(point_a, point_b):
    x_distance = (point_a[0] - point_b[0])
    y_distance = (point_a[1] - point_b[1])
    
    distance = np.sqrt (x_distance * x_distance + y_distance*y_distance)
    return distance

def GetAngleOfTwoPoints(point_a, point_b):
    angle = math.atan2(point_b[1] - point_a[1], point_b[0] - point_a[0]) * 180.0/np.pi
    fix_angle = int((int(angle) + 360) % 360)
    return fix_angle

def IsRectCornersReasonable(rect_corners, image_width):
    """ 
     一组策略，判断4个 corner 是否可以形成一个可信度高的矩形(有透视变换效果，所以肯定不是标准的长方形，而是一个梯形或平行四边形)
     4个 point 是已经经过ArrangeRectPoints排过序的
     4 points top-left, top-right, bottom-right, bottom-left, index are 0, 1, 2, 3
    """
    
    if len(rect_corners) == 4:
        #rect_points = rect_corners
        rect_points = []
        
        rect_points.append(rect_corners[0][0])
        rect_points.append(rect_corners[1][0])
        rect_points.append(rect_corners[2][0])
        rect_points.append(rect_corners[3][0])
        
        segment_0_to_1 = (rect_points[0][0], rect_points[0][1], rect_points[1][0], rect_points[1][1])
        segment_1_to_2 = (rect_points[1][0], rect_points[1][1], rect_points[2][0], rect_points[2][1])
        segment_2_to_3 = (rect_points[2][0], rect_points[2][1], rect_points[3][0], rect_points[3][1])
        segment_3_to_0 = (rect_points[3][0], rect_points[3][1], rect_points[0][0], rect_points[0][1])
        
        rect_segments = []
        rect_segments.append(segment_0_to_1)
        rect_segments.append(segment_1_to_2)
        rect_segments.append(segment_2_to_3)
        rect_segments.append(segment_3_to_0)
        
        if not (IsSegmentsHasSameSegment(rect_corners[0][1], segment_0_to_1, image_width)) and (IsSegmentsHasSameSegment(rect_corners[1][1], segment_0_to_1, image_width)):
            return False
        
        if not (IsSegmentsHasSameSegment(rect_corners[1][1], segment_1_to_2, image_width)) and (IsSegmentsHasSameSegment(rect_corners[2][1], segment_1_to_2, image_width)):
            return False
        
        if not (IsSegmentsHasSameSegment(rect_corners[2][1], segment_2_to_3, image_width)) and (IsSegmentsHasSameSegment(rect_corners[3][1], segment_2_to_3, image_width)):
            return False
        
        if not (IsSegmentsHasSameSegment(rect_corners[3][1], segment_3_to_0, image_width)) and (IsSegmentsHasSameSegment(rect_corners[0][1], segment_3_to_0, image_width)):
            return False
        
        #第二组策略，根据四边形的形状
        distance_of_0_to_1 = PointsDistance(rect_points[0], rect_points[1])
        distance_of_1_to_2 = PointsDistance(rect_points[1], rect_points[2])
        distance_of_2_to_3 = PointsDistance(rect_points[2], rect_points[3])
        distance_of_3_to_0 = PointsDistance(rect_points[3], rect_points[0])
        
        #计算两组对边的比例(0.0 -- 1.0的值)
        #两条对边(标准矩形的时候，就是两条平行边)的 minLength / maxLength，不能小于0.5，否则就认为不是矩形(本来是把这个阈值设置为0.8的，但是因为图片都是缩放后进行的处理，长宽比有很大的变化，所以把这里的过滤条件放宽一些，设置为0.5)
        #distance_of_0_to_1 和 distance_of_2_to_3 是两条对边
        ratio1 = np.min([distance_of_0_to_1, distance_of_2_to_3]) / np.max([distance_of_0_to_1, distance_of_2_to_3])
        ratio2 = np.min([distance_of_1_to_2, distance_of_3_to_0]) / np.max([distance_of_1_to_2, distance_of_3_to_0])
        
        if (ratio1 >= kRectOpposingSidesMinRatio and ratio2 >=kRectOpposingSidesMinRatio):
            #两组对边，至少有一组是接近平行状态的(根据透视角度的不同，四边形是一个梯形或者平行四边形)
            
            angle_top = GetAngleOfTwoPoints(rect_points[1], rect_points[0])
            angle_bottom = GetAngleOfTwoPoints(rect_points[2], rect_points[3])
            
            angle_right = GetAngleOfTwoPoints(rect_points[2], rect_points[1])
            angle_left = GetAngleOfTwoPoints(rect_points[3], rect_points[0])
            
            diff1 = int(abs(angle_top - angle_bottom))
            diff2 = int(abs(angle_right - angle_left))
            diff1 = diff1 % 90
            diff2 = diff2 % 90
            
            if (diff1 <= 8 and diff2 <= 8):
                return True
            
            if (diff1 <= 8 and diff2 <= 45):
                return True
            
            if (diff1 <= 45 and diff2 <= 8):
                return True
        else:
            return False
    else:
        return False
 

def ocr_scanner(edge_image, ori_image, draw_debug_image):
    #hed网络输出的边缘图像进行float转换，必须进行该步骤，否则后续处理无法进行
    
    corners_image = ori_image.copy()
    line_image = ori_image.copy()
    edge_image = edge_image.astype(float)
    #二值化，找线段
    _,binary_image = cv2.threshold(edge_image, 128, 255, cv2.THRESH_BINARY)
    
    binary_image = binary_image.astype(int)
    
    gray_image = np.ones((256, 256), dtype = np.uint8)
    for i in range(binary_image.shape[1]):
        for j in range(binary_image.shape[0]):
            gray_image[i][j] = binary_image[i][j]
    #这组参数，可以检测到比较小的矩形，但是对干扰物就更敏感了，很容易检测出矩形框之外的短线段
    lines = cv2.HoughLinesP(gray_image, 1, np.pi * 1/180, kHoughLinesPThreshold, kHoughLinesPMinLinLength, kHoughLinesPMaxLineGap)
    
    #<3>线段转换成 参考直线(其实是正好被 image 完整尺寸截断的线段)，并且做一轮过滤
    ref_line_and_segment_pairs = []
    
    for i in range(len(lines)):
        segment = lines[i][0]   #segment为[[x1,y1,x2,y2]]
        ref_line = GetRefLine(segment, edge_image.shape[1], edge_image.shape[0])
        #print(segment, ref_line)
        
        #线段长度过滤
        segment_length = np.sqrt((float(segment[1] - segment[3])) * (float(segment[1] - segment[3])) + (float(segment[0] - segment[2])) * (float(segment[0] - segment[2])))
        if (segment_length > kHoughLinesPMinLinLength):
            ref_line_and_segment_pairs.append([ref_line, segment])
    print('ref_line_and_segment_pairs', len(ref_line_and_segment_pairs))
    #<4>合并临近的直线
    merged_ref_line_and_segment_pairs = MergeRefLineAndSegmentPairs(ref_line_and_segment_pairs, edge_image.shape[1], edge_image.shape[0])
    print('merged_ref_line_and_segment_pairs',len(merged_ref_line_and_segment_pairs))
    ref_lines = []
    segments = []
    for i in range(len(ref_line_and_segment_pairs)):
        ref_line_and_segment = ref_line_and_segment_pairs[i]
        ref_line = ref_line_and_segment[0]
        segment = ref_line_and_segment[1]
        
        ref_lines.append(ref_line)
        segments.append(segment)
        
    if draw_debug_image:
        for i in range(len(segments)):
            v = segments[i]
            if draw_debug_image:
                cv2.line(ori_image, (v[0], v[1]), (v[2], v[3]), (0, 255, 0))
    cv2.imwrite('segments.jpg', ori_image)
    
    #<5>寻找segment线段的交叉点以及过滤
    corners = []
    
    for i in range(len(segments)):
        for j in range(i+1, len(segments)):
            segment_a = segments[i]
            segment_b = segments[j]
            
            #求两条线段的交点
            intersection_point = GetSegmentIntersection(segment_a, segment_b)
            if intersection_point is not None:
                if (intersection_point[0] >=0 and intersection_point[1] >= 0 and intersection_point[0] <= edge_image.shape[1] and intersection_point[1] <= edge_image.shape[0]):
                    thetaA = int(GetAngleOfLine(segment_a))
                    thetaB = int(GetAngleOfLine(segment_b))
                    
                    angle = abs(thetaA - thetaB)
                    angle = angle % 180
                    
                    if (angle >= kIntersectionMinAngle and angle <= kIntersectionMaxAngle):
                        c_segments = []
                        c_segments.append(segment_a)
                        c_segments.append(segment_b)
                        corners.append([intersection_point, c_segments])
    print('corners', corners[0])
    
    #对交叉点进行第二轮过滤，两个点如果很接近，则合并成同一个点， 并且用他们的平均值来标示该点
    average_corners = []
    for i in range(len(corners)):
        corner = corners[i]
        if (len(average_corners)) == 0:
            average_corners.append(corner)
        else:
            isCloser = False
            for j in range(len(average_corners)):
                c = average_corners[j]
                #print('average_corners', c)
                
                corner_point = corner[0]
                c_point = c[0]
                diff_x, diff_y = corner_point[0] - c_point[0], corner_point[1] - c_point[1]
                #print('diff_x, diff_y', diff_x, diff_y)
                distance = np.sqrt(diff_x*diff_x+diff_y*diff_y)
                
                if (distance < kCloserPointMaxDistance):
                    newCornet = []
                    new_point = (corner_point[0] + c_point[0])/2, (corner_point[1] + c_point[1])/2
                    
                    #还要合并每个cornet的segment线段数组
                    newCornet_segments = []
                    segment_a = corner[1]
                    segment_b = c[1]
                    #newCornet_segments.append(segment_a)
                    #newCornet_segments.append(segment_b)
                    newCornet_segments.extend(segment_a)
                    newCornet_segments.extend(segment_b)
                    #newCornet.append([new_point, newCornet_segments])
                    #average_corners[j] = newCornet
                    average_corners[j] = [new_point, newCornet_segments]
                    isCloser = True
            if (isCloser == False):
                average_corners.append(corner)
                    ##################
    print('average_corners', len(average_corners))
    
    if (draw_debug_image):
        for i in range(len(average_corners)):
            corner = average_corners[i]
            (x1, x2) = point = corner[0]
            cv2.circle(corners_image, (int(x1), int(x2)), 3, (255, 0, 0), 2)
            
            segments = corner[1]
            for j in range(len(segments)):
                v = segments[j]
                cv2.line(corners_image, (v[0], v[1]), (v[2], v[3]), (0, 255, 255), 3)
    cv2.imwrite('corners_image.jpg', corners_image)
    
    
    #<6>寻找四边形
    if (len(average_corners))>=4:
        #至少要有4个点，才算是矩形
        
        maxPerimeter = 0.0
        
        #rect_corners = []
        rect_corners_with_max_perimeter = []
        rect_points_with_max_perimeter = []
        results = []
        #4重循环的计算量还是有点大
        for i in range(len(average_corners)-4):
            for j in range(i+1, len(average_corners) - 3):
                for m in range(j+1, len(average_corners) - 2):
                    for n in range(m+1, len(average_corners) - 1):
                        rect_corners = []
                        rect_corners.append(average_corners[i])
                        rect_corners.append(average_corners[j])
                        rect_corners.append(average_corners[m])
                        rect_corners.append(average_corners[n])
                        
                        #对四个点按照顺时针方向排序
                        rect_corners = ArrangeRectCorners(rect_corners)
                        #print('rect_corners',rect_corners)
                        #如果不是一个合理的四边形，则直接排除
                        if IsRectCornersReasonable(rect_corners, edge_image.shape[1] == False):
                            continue
                        rect_points = []
                        #rect_points.append(rect_corners[0][0])
                        #rect_points.append(rect_corners[1][0])
                        #rect_points.append(rect_corners[2][0])
                        #rect_points.append(rect_corners[3][0])
                        rect_points.append([int(rect_corners[0][0][0]), int(rect_corners[0][0][1])])
                        rect_points.append([int(rect_corners[1][0][0]), int(rect_corners[1][0][1])])
                        rect_points.append([int(rect_corners[2][0][0]), int(rect_corners[2][0][1])])
                        rect_points.append([int(rect_corners[3][0][0]), int(rect_corners[3][0][1])])
                        
                        #或者用最大面积
                        rect_points = np.array(rect_points)
                        #print('rect_points',rect_points)
                        perimeter = cv2.contourArea(rect_points)
                        
                        if (perimeter > maxPerimeter):
                            maxPerimeter = perimeter
                            rect_corners_with_max_perimeter = rect_corners
                            rect_points_with_max_perimeter = rect_points
        
        if len(rect_points_with_max_perimeter) == 4:
            results = rect_points_with_max_perimeter
            if draw_debug_image:
                top_left = tuple(results[0])
                top_right = tuple(results[1])
                bottom_right = tuple(results[2])
                bottom_left = tuple(results[3])
                
                print('top_left', top_left, top_right, bottom_right, bottom_left)
                cv2.line(line_image, top_left, top_right, (255, 0, 0), 3)
                cv2.line(line_image, top_right, bottom_right, (255, 0, 0), 3)
                cv2.line(line_image, bottom_right, bottom_left, (255, 0, 0), 3)
                cv2.line(line_image, bottom_left, top_left, (255, 0, 0), 3)
            cv2.imwrite('line_image.jpg', line_image)
    
    if len(results) == 4:
        find_rect = True
    else:
        find_rect = False
    return (find_rect, results, ori_image, corners_image, line_image)

**Comment by mayidu** [comment]
您好！我现在把你后处理部分的cpp生成动态库文件，在python里直接调用，测试了一下，发现有好几个图像，hed处理的结果挺好的，但是后处理后找不到四个点的坐标，请问，要优化的话，能否给点思路，谢谢！
图例：
原图
![image](https://user-images.githubusercontent.com/29938271/58956311-94265c00-87d0-11e9-8b65-5dde5a6e248d.png)

hed结果：
![image](https://user-images.githubusercontent.com/29938271/58956275-82dd4f80-87d0-11e9-8ba2-f978940a1ef6.png)

后处理结果，如果没有找到4个点，则返回图像的四个顶点
![image](https://user-images.githubusercontent.com/29938271/58956198-60e3cd00-87d0-11e9-8d3f-8f1120a034b5.png)

**Comment by fengjian0106** [comment]
@mayidu 这个不是优化的问题，
![image](https://user-images.githubusercontent.com/2616680/58964334-4c5c0080-87e1-11e9-96de-d8e1f364426f.png)
你检测到的这个边缘图，质量已经是很高的了，OpenCV部分的算法，不至于连这种场景都检测不出来，我怀疑是python直接使用这个C++引出的其他问题。

我的C++代码部分，fm_ocr_scanner.cpp 里面有一个宏定义 ENABLE_DEBUG_MODE，打开这个宏定义，然后 std::tuple<bool, std::vector<cv::Point>, std::vector<cv::Mat> > ProcessEdgeImage(cv::Mat edge_image, cv::Mat color_image, bool draw_debug_image) 函数返回的tuple的最后一个值，是调试目的的4个OpenCV Mat，你可以把它们绘制出来看看效果。这份代码里，iOS demo 是可以绘制这些debug image的，如果你能运行iOS demo，可以用这个做对比。

另外，在真实的产品中，这套算法是在实时的视频流上做检测，所以整体优化的时候，即便某一帧图像上面没有检测到矩形的4个点，也没有关系，只要后续或之前的帧上面检测到过4个点，加上一些稳定性检测的策略，像你遇到的这种背景并不复杂的场景，是有很高概率检测出顶点的

**Comment by mayidu** [comment]
是这样的，由于python c++的混合编程问题，我把你的输出变了一下，我直接从最后的results里面拿出来最终检测的四个角点的坐标，以及face_rect，这几个数据的输出，具体里面的debug image的图像，我再输出一下看看，我主要是觉得，对于hed出来的结果不好的情况，检测不到四个角点是可以理解的，但是对于这种情况，不应该出现这样的问题，我再把结果输出出来看看，感谢您的回复，后续有什么问题还需获得您的帮助，谢谢！

**Comment by mayidu** [comment]
您好，我把debug 的图像保存下来了，发给你看一下：
lines_image:
![image](https://user-images.githubusercontent.com/29938271/59000189-f10b2c00-883b-11e9-9162-c580e1edcfbf.png)
corners_image:
![image](https://user-images.githubusercontent.com/29938271/59000202-fff1de80-883b-11e9-87a2-e7c7f800ed5c.png)

最后corners只找到了3个点，不够四个点，所有最后返回了fact_rect为0

**Comment by fengjian0106** [comment]
kHoughLinesPThreshold = 20
kHoughLinesPMinLinLength = 20.0
kHoughLinesPMaxLineGap = 3.0

kMergeLinesMaxDistance = 5
kIntersectionMinAngle = 45
kIntersectionMaxAngle = 135
kCloserPointMaxDistance = 6.0
kRectOpposingSidesMinRatio = 0.5
kPointOnLineMaxOffset = 8
kSameSegmentsMaxAngle = 5
这些参数是可调的，你可以试一下。

我的使用场景是在视频流上做连续检测，单帧图片检测不到对我的业务流程影响不大，用手机拍摄的时候，总是会有轻微的抖动的，而且操作者会有选择性的移动手机寻找拍摄角度，在这个过程中，更上层的算法会持续判断是否有检测到四个点，同时判断前后几次检测到的四个点的坐标是否处于一个稳定状态，满足这些条件的时候，就会自动把矩形区域截取出来。上面列出来的这几个参数，是针对这种操作场景做的优化和调参。我的这个iOS demo里面，并没有演示这个额外的判断稳定性的流程。
你的业务场景如果只是对静态图片做检测的话，试着调一下那些参数吧。

**Comment by mayidu** [comment]
太感谢，我试着调一下，目前我主要是针对一张图像去检测，同时也在训练模型中，感谢您的分享和回复！

**Comment by yux94** [comment]
你好 请问可以请教一下 如何将后处理部分的cpp生成动态库文件，并在python里调用吗？我遇到的情况是调用so文件时报错：undefined symbol _ZN2cv3Mat10deallocaleEv

**Comment by mayidu** [comment]
需要修改传入参数的类型，然后直接生成so文件就可以正常调用了，但是传参的数据类型得定义好，要python个c++对应的

**Comment by yux94** [comment]
谢谢回复，请问您是否方便提供一下调用部分的代码吗？我将ProcessEdgeImage函数部分的传入参数CV mat改写成int* 以及int型等，但是调用时，且仅是在ctypes.cdll.LoadLibrary 时仍报了如上的错误，请问是否是缺少一些库呢？如opencv等？

**Comment by xxxxxxxiao** [comment]
你好！请问能把后处理的py文件分享一下嘛？谢谢！

**Comment by renmoqiqi** [comment]
静态图片怎么优化的，能分享下么
