### ISSUE TITLE
关于tensorflow静态库依赖

### ISSUE THREAD

**Issue by chaoyueziji** [fengjian0106/hed-tutorial-for-document-scanning#54]
小白求教，不好意思。。。
我看大佬是根据tensorflow静态库然后编译链接成自己的sdk，主要想求教几个问题：
 在安装包的过程中是不是还是需要将tensorflow-core.a进行打包进去，因为我看到你最终的sdk才8M左右，还是说只需要将这8M的sdk进行打包进安装包中

**Comment by fengjian0106** [comment]
是的，xcode中，最终的app还是需要链接 tensorflow-core.a 静态库
