### ISSUE TITLE
Logic for text detection on cards

### ISSUE THREAD

**Issue by ajinkya933** [fengjian0106/hed-tutorial-for-document-scanning#60]
Hello,

Can the same algorithm that you used to find document borders also be used to find text in a image. Provided I give text annotation data as an input to train. 

I have cropped text photos, and background photos.
Using your ios simulator If I generate files and follow your same steps will your code work to find text on cards?

Regards
Ajinkya

**Comment by fengjian0106** [comment]
HED is just detecting edge of object, you want find text, I think what you want to do is detecting bound box of some text，did you ? If you want bound box of text, you can have a look at  https://github.com/whitelok/image-text-localization-recognition

**Comment by ajinkya933** [comment]
Yes, I want to detect bounding box for text on drivers liscences

**Comment by fengjian0106** [comment]
> Yes, I want to detect bounding box for text on drivers liscences

So, HED is not a good choice for text bounding box detecing
