### ISSUE TITLE
您好，能否分享下Android版的执行基于 OpenCV 实现的找点算法呢，非常感谢

### ISSUE THREAD

**Issue by xieyongxiong** [fengjian0106/hed-tutorial-for-document-scanning#64]

**Comment by fengjian0106** [comment]
> _No description provided._

找点算法是C++实现的，可以跨平台，在Android的NDK那一层也是可以用的

**Comment by szuwest** [comment]
@fengjian0106 想问一下为什么库中4个点的算法，你们没有用OpenCV里的findContours方法，而是自己写一些算法来找点？是因为findContours有什么缺陷达不到你们的要求吗？我看网上很多库都是采样这种方法来找点的，所以想问问你们是基于什么考虑。
谢谢

**Comment by fengjian0106** [comment]
@szuwest findContours 效果不好，我的博客里有解释 http://fengjian0106.github.io/2017/05/08/Document-Scanning-With-TensorFlow-And-OpenCV/

findContours 函数也只能检测闭合的多边形的顶点，但是并不能确保这个多边形就是一个合理的矩形。因此在我们的第一版技术方案中，对这两个关键步骤，进行了大量的改进和调优，概括起来就是：

改进 canny 算法的效果，增加额外的步骤，得到效果更好的边缘检测图
针对 canny 步骤得到的边缘图，建立一套数学算法，从边缘图中寻找出一个合理的矩形区域
