### ISSUE TITLE
麻烦问一下为什么几万张图片， 我训练了二十几万步还没训练完（花了几天）

### ISSUE THREAD

**Issue by xieyongxiong** [fengjian0106/hed-tutorial-for-document-scanning#65]
麻烦问一下为什么几万张图片， 我训练了二十几万步还没训练完（花了几天）
`Step: 262930, Current Mean Loss: 0.00067567510996
Step: 262935, Current Mean Loss: 0.000692806439474
Step: 262940, Current Mean Loss: 0.000439939438365
Step: 262945, Current Mean Loss: 0.000606557819992
Step: 262950, Current Mean Loss: 0.000613953918219
Step: 262955, Current Mean Loss: 0.000287700153422
Step: 262960, Current Mean Loss: 0.000336370721925
Step: 262965, Current Mean Loss: 0.000487249868456
Step: 262970, Current Mean Loss: 0.00057760317577
Step: 262975, Current Mean Loss: 0.000349914800609
Step: 262980, Current Mean Loss: 0.000262093089987
Step: 262985, Current Mean Loss: 0.000596537487581
Step: 262990, Current Mean Loss: 0.000655797543004
Step: 262995, Current Mean Loss: 0.00037652591709
Step: 263000, Current Mean Loss: 0.000553493737243
Step: 263005, Current Mean Loss: 0.000813497463241
Step: 263010, Current Mean Loss: 0.000388360233046
Step: 263015, Current Mean Loss: 0.000841892790049
Step: 263020, Current Mean Loss: 0.000386611325666
Step: 263025, Current Mean Loss: 0.000679999473505
Step: 263030, Current Mean Loss: 0.000298142753309
Step: 263035, Current Mean Loss: 0.000452324340586
Step: 263040, Current Mean Loss: 0.000683541409671
Step: 263045, Current Mean Loss: 0.000850292213727
Step: 263050, Current Mean Loss: 0.000502695911564
Step: 263055, Current Mean Loss: 0.000517184380442
Step: 263060, Current Mean Loss: 0.000687578809448
Step: 263065, Current Mean Loss: 0.000568915857002
Step: 263070, Current Mean Loss: 0.000535387545824
Step: 263075, Current Mean Loss: 0.000429486128269
Step: 263080, Current Mean Loss: 0.000511971360538
Step: 263085, Current Mean Loss: 0.000414077774622
Step: 263090, Current Mean Loss: 0.000775712484028
Step: 263095, Current Mean Loss: 0.000847970251925
Step: 263100, Current Mean Loss: 0.000988250481896
Step: 263105, Current Mean Loss: 0.000489166122861
Step: 263110, Current Mean Loss: 0.000803058734164
Step: 263115, Current Mean Loss: 0.000522677146364`

**Comment by fengjian0106** [comment]
命令行参数iterations的初始默认值，我设置的很大
