### ISSUE TITLE
问题：目前开源的预训练模型是有多大的 training set 训练的？

### ISSUE THREAD

**Issue by xraywu** [fengjian0106/hed-tutorial-for-document-scanning#67]
您好，想问下目前仓库里开源的预训练模型是用多大的 training set 实现的？是只用了 csv 文件里的 11 个样本吗？

**Comment by fengjian0106** [comment]
@xraywu 样本量比 csv 里的大很多，github 不适合放这么多样本，所以放上来的只是演示性质的。
但是所有的样本都是基于 sample_images 目录的图片生成出来的，生成样本的iOS代码也在这个项目里，跑一遍就可以生成出来了。

另外，还可以根据自己的需求，在 sample_images 目录里添加更多的原始图片，生成更多的样本。
