### ISSUE TITLE
code conversion of tflite fails 

### ISSUE THREAD

**Issue by ajinkya933** [fengjian0106/hed-tutorial-for-document-scanning#69]
I am following your code and trying to convert pb to tflite. However it fails with error:

```
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: Placeholder is_training should be specied by input_arrays.
```

Here is my pb file:
https://drive.google.com/drive/folders/1ZMCSSNszimpQ-phMKg1vFzBDV5undlMF?usp=sharing

here is my conversion script
```
tflite_convert --output_file=hed_graph.tflite --graph_def_file=hed_graph.pb --input_arrays=hed_input is_training --output_arrays=hed/dsn_fuse/conv2d/BiasAdd
```

live code link: https://colab.research.google.com/drive/1YZb7TcYtvT-BQOjNE7cKlO8Wk3UEOpTl?usp=sharing

How can I remove this error ?

**Comment by fengjian0106** [comment]
@ajinkya933 hi, see https://github.com/fengjian0106/hed-tutorial-for-document-scanning/issues/45 and https://github.com/tensorflow/tensorflow/issues/24477
