### ISSUE TITLE
能否提供Android demo

### ISSUE THREAD

**Issue by EricHuiK** [fengjian0106/hed-tutorial-for-document-scanning#72]

**Comment by fengjian0106** [comment]
@EricHuiK  没计划直接提供一个可运行的 Android demo了，但是你可以参考 https://github.com/pqpo/SmartCropper 这个Android项目，里面的神经网络部分，是用的我的这个模型。
另外，你也可以尝试自己移植，代码中基于 OpenCV 的部分，也是可以直接在 Android 上运行的，只依赖 OpenCV。

**Comment by EricHuiK** [comment]
感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fengjian0106/hed-tutorial-for-document-scanning"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 中午1:35
收件人:&nbsp;"fengjian0106/hed-tutorial-for-document-scanning"<hed-tutorial-for-document-scanning@noreply.github.com&gt;;
抄送:&nbsp;"流年啊你能耐我何"<875824970@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [fengjian0106/hed-tutorial-for-document-scanning] 能否提供Android demo (#72)





 
@EricHuiK  没计划直接提供一个可运行的 Android demo了，但是你可以参考 https://github.com/pqpo/SmartCropper 这个Android项目，里面的神经网络部分，是用的我的这个模型。
 另外，你也可以尝试自己移植，代码中基于 OpenCV 的部分，也是可以直接在 Android 上运行的，只依赖 OpenCV。
