### ISSUE TITLE
训练图片与实际图片大小差距较大，导致缩放恢复之后定位不准

### ISSUE THREAD

**Issue by bikerr** [fengjian0106/hed-tutorial-for-document-scanning#73]
![dsn_fuse](https://user-images.githubusercontent.com/14155359/90583071-dbe0aa00-e201-11ea-896f-89f3644cfd73.png)
1.如果图片过大，比如3000x4000 的图片 缩放到256*256 根据算法 恢复角点会通过缩放形式 但是这种形式会导致定位误差较大
2.通过HED生成的图片(如上图所示) 边缘线较粗，根据后续算法合并线段获取平均值也会导致边缘线误差较大

**Comment by fengjian0106** [comment]
@bikerr  如果你的样本图片都是这么大尺寸的，你可以考虑修改一下模型，适当的放大一下input image的size，同时，还需要针对你的这种大尺寸的input image，专门标注一批高精度的样本数据，这样可能会有一些改善。
这种神经网络模型，还是要靠数据"喂"出来的，数据的质量高，效果就会更好。
