### ISSUE TITLE
HED网络裁剪

### ISSUE THREAD

**Issue by bikerr** [fengjian0106/hed-tutorial-for-document-scanning#75]
HED网络裁剪是否有哪些依据 或者进行过相关对比 裁剪比较大 是否对后续代替canny 算子造成比较大的影响 目前测试过程中发现 部分预测图片 HED输出边缘过于少 后续步骤很难进行优化

**Comment by fengjian0106** [comment]
训练样本的丰富程度，也很重要。我做裁剪，主要是为了把模型塞到手机里，所以裁剪比较狠。
