### ISSUE TITLE
请问下作者使用c++加载这个pb格式模型文件

### ISSUE THREAD

**Issue by HelloFish-2016** [fengjian0106/hed-tutorial-for-document-scanning#78]
现在想在服务端使用c++加载这个pb文件，然后打成可执行文件，想问下作者有这个范例吗？

**Comment by HelloFish-2016** [comment]
当我在c++里使用cv::dnn::readNetFromTensorflow(model)时会抛出错误
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.4.0) /home/mango/opencv-4.4.0/modules/dnn/src/tensorflow/tf_importer.cpp:553: error: (-2:Unspecified error) Input layer not found: hed/dsn5/conv2d_transpose/Shape in function 'connect'
google了一遍也没找到解答

**Comment by fengjian0106** [comment]
在server端，用tensorflow的C++ api来加载。我没用opencv加载过这个模型，可能会有各种问题
