### ISSUE TITLE
./trained-hed.py tooks too much time.

### ISSUE THREAD

**Issue by LoveU3tHousand2** [fengjian0106/hed-tutorial-for-document-scanning#80]
3 background images x 4 rect images tooks me 42 hours and not finished yet.
Is that normal ?
Somebody help~

**Comment by fengjian0106** [comment]
if you use CPU, default will iterations 90000000 times,  it will take long time.
To me, I did not wait iterations ends, but I will have a look at debug_output_image folder, if the image is good enough, I will stop training.

By the way,  3 background images x 4 rect images is too few, it's not a good training data set

**Comment by LoveU3tHousand2** [comment]
Thanks for your reply!!
Can you advice me the time of iterations for 600b x 3000f images?
然后就是，我好像注意到了您也是中国人。。

Sent from my iPhone

On Sep 23, 2020, at 11:24 AM, fengjian <notifications@github.com> wrote:

﻿

if you use CPU, default will iterations 90000000 times, it will take long time.
To me, I did not wait iterations ends, but I will have a look at debug_output_image folder, if the image is good enough, I will stop training.

By the way, 3 background images x 4 rect images is too few, it's not a good training data set

**Comment by LoveU3tHousand2** [comment]
How does the good enough image in debug_output_image folder look like?

**Comment by fengjian0106** [comment]
样本量肯定是越大越好的，我是合成的样本，背景图和前景图各自都有几百或上千张，然后合成的过程中，会做样本增强处理
