### ISSUE TITLE
关于在evaluate_hed.py里使用gpu计算的速度问题

### ISSUE THREAD

**Issue by HelloFish-2016** [fengjian0106/hed-tutorial-for-document-scanning#81]
使用cpu计算时 ，跑evaluate_hed.py代码输入一张图片得到结果大概需要七八百毫秒，我改成了指定gpu进行计算，时间反而变慢了，需要两三秒，想请问下作者能提供点思路吗

**Comment by HelloFish-2016** [comment]
> 使用cpu计算时 ，跑evaluate_hed.py代码输入一张图片得到结果大概需要七八百毫秒，我改成了指定gpu进行计算，时间反而变慢了，需要两三秒，想请问下作者能提供点思路吗

还是说需要重新使用gpu训练

**Comment by fengjian0106** [comment]
我没用GPU计算过，这个模型并不大，用CPU训练一天就能看到很明显的效果了。CPU 跑evaluate其实也要不了7、8百毫秒，你看到的800毫秒，应该是还包含了模型加载等额外的时间。
用GPU跑evaluate反而慢了，可能是代码层面的原因，这份代码没有适配过GPU，可能是有一些坑吧
