### ISSUE TITLE
合成训练样本时，Imac 意外重启，很多次

### ISSUE THREAD

**Issue by LoveU3tHousand2** [fengjian0106/hed-tutorial-for-document-scanning#82]
机器是Imac 2015年 21.5款
处理器 2.8 GHz 四核Intel Core i5
内存 8 GB 1867 MHz DDR3
显卡：Intel Iris Pro Graphics 6200 1536 MB
硬盘：500G 三星 EVO 860
b_image ：290张 r_image ： 1000张

请问这个配置跑起来会有问题吗， 或者说 跑的时候关机还有什么其他影响因素吗？ 比如图片的质量？

**Comment by fengjian0106** [comment]
有crash日志、系统日志吗？这个很难说是哪里的问题，要找线索

**Comment by LoveU3tHousand2** [comment]
我这边想问一下，合成样本图片那一步能够用几台机器跑不同的前景背景图片然后再把图片集中起来去训练吗

**Comment by fengjian0106** [comment]
> 我这边想问一下，合成样本图片那一步能够用几台机器跑不同的前景背景图片然后再把图片集中起来去训练吗

最好再检查一下代码，避免在不同的机器上合成出同名的图片
