### ISSUE TITLE
进行2.1步骤的时候还是系统崩溃重启 如下是崩溃日志

### ISSUE THREAD

**Issue by LoveU3tHousand2** [fengjian0106/hed-tutorial-for-document-scanning#83]
1. 麻烦帮忙看看到底是什么问题，跪谢 
2. 如果是硬件瓶颈的话 需要提升的硬件有哪些，能推荐一款mac吗

[crash.txt](https://github.com/fengjian0106/hed-tutorial-for-document-scanning/files/5287925/crash.txt)

**Comment by LoveU3tHousand2** [comment]
而且在运行过这个xporj的测试mac上都出现了屏幕闪花屏的现象， 这是为什么呢。

**Comment by fengjian0106** [comment]
这个日志是watchdogd看门狗超时了，没有办法直接定位到应用层代码出问题的地方，感觉是程序跑死了，或者是CPU跑死循环了。现在的线索没有办法定位，你试一下减少图片的数量，再运行看看。这个合成图片的代码，是在两年前的mac和当时的操作系统版本、xcode版本、iOS版本上运行的。

另外，你说遇到了花屏，这个不太正常，而且感觉是系统层面的问题，你的xcode、模拟器环境，是app store安装的？还是单独下载安装的，或者你重装xcode再试试
