### ISSUE TITLE
在 python 环境中测试 HED 网络，很慢

### ISSUE THREAD

**Issue by mengxiangxiang414** [fengjian0106/hed-tutorial-for-document-scanning#86]
我的环境：

> 系统：Ubuntu
> gpu显存：11G，
> 内存：16G
> tensorflow-gpu:1.8

直接下载下了您的代码进行了测试，即：在 python 环境中测试 HED 网络。
`python evaluate_hed.py --checkpoint_dir checkpoint \
                       --image test_image/test27.jpg \
                       --output_dir test_image`
测试图片大小：test27.jpg, 600*800
结果：

1. 获得feature map的过程特别长，2~3秒
2. 在后面进行https://github.com/fengjian0106/hed-tutorial-for-document-scanning/blob/7e168f4e1230e691ef51df34fb807c8d55e61148/evaluate_hed.py#L72-L81 的时候报错，显存不够。11G还不够吗？我有点疑惑，请老哥您指点一下。

**Comment by fengjian0106** [comment]
不用用GPU版本，直接用CPU就行，我是前两年训练的模型，CPU够用的。没有适配过GPU，用的tf库也比较老了，很长时间没有更新了

**Comment by mengxiangxiang414** [comment]
@fengjian0106 好的，谢谢，我换CPU果然可以了。
