### ISSUE TITLE
ios opencv 用最新的sdk报错

### ISSUE THREAD

**Issue by weinixuehao** [fengjian0106/hed-tutorial-for-document-scanning#9]
tensorflow::Status load_graph_status = ReadBinaryProto(tensorflow::Env::Default(), pbPath, &graphDef);
在这行bad_access_error，博主有遇到过？

**Comment by fengjian0106** [comment]
@weinixuehao ReadBinaryProto 是 TensorFlow 的函数，这里跟 OpenCV 没有直接的关联。你遇到的是 crash 吗，错误堆栈贴出来看看
